In [1]:
# HYP - Random Forest - Period 1

In [2]:
from sklearn import tree
import pandas as pd

In [3]:
df = pd.read_csv('../Resources/HYP_final_data.csv')
df.head(20)

,RANDID,SEX,TOTCHOL,AGE,SYSBP,DIABP,CURSMOKE,CIGPDAY,BMI,DIABETES,...,PREVMI,PREVCHD,PREVAP,PREVSTRK,PREVHYP,TIME,PERIOD,DEATH,HYPERTEN,TIMEHYP
0,2448,1,195.0,39,106.0,70.0,0,0.0,26.97,0,...,0,0,0,0,0,0,1,0,0,8766
1,6238,2,250.0,46,121.0,81.0,0,0.0,28.73,0,...,0,0,0,0,0,0,1,0,0,8766
2,9428,1,245.0,48,127.5,80.0,1,20.0,25.34,0,...,0,0,0,0,0,0,1,0,0,8766
3,11252,2,285.0,46,130.0,84.0,1,23.0,23.10,0,...,0,0,0,0,0,0,1,0,1,4285
4,12629,2,205.0,63,138.0,71.0,0,0.0,33.11,0,...,0,0,0,0,0,0,1,0,1,2212
5,12806,2,313.0,45,100.0,71.0,1,20.0,21.68,0,...,0,0,0,0,0,0,1,0,1,8679
6,16799,2,254.0,50,133.0,76.0,0,0.0,22.91,0,...,0,0,0,0,0,0,1,0,0,8766
7,19304,2,247.0,43,131.0,88.0,0,0.0,27.64,0,...,0,0,0,0,0,0,1,0,0,8766
8,33555,2,291.0,46,112.0,78.0,1,20.0,23.38,0,...,0,0,0,0,0,0,1,1,0,1442
9,34689,2,195.0,38,122.0,84.5,1,5.0,23.24,0,...,0,0,0,0,0,0,1,0,1,2157
10,36459,1,195.0,41,139.0,88.0,0,0.0,26.88,0,...,0,0,0,0,0,0,1,0,1,1469
11,40435,2,190.0,42,108.0,70.5,1,30.0,21.59,0,...,0,0,0,0,0,0,1,0,1,5933
12,43770,2,234.0,52,148.0,78.0,0,0.0,34.17,0,...,0,0,0,0,0,0,1,1,1,723
13,45464,2,215.0,52,132.0,82.0,1,20.0,25.11,0,...,0,0,0,0,0,0,1,0,1,2177
14,54224,1,294.0,47,102.0,68.0,1,20.0,24.18,0,...,0,0,0,0,0,0,1,1,0,430
15,66472,2,247.0,60,130.0,88.0,0,0.0,30.36,0,...,0,0,0,0,0,0,1,1,1,1463
16,67905,1,295.0,36,102.0,68.0,1,35.0,28.15,0,...,0,0,0,0,0,0,1,0,1,2954
17,68194,1,226.0,43,115.0,85.5,1,43.0,27.57,0,...,0,0,0,0,0,0,1,0,1,6199
18,68397,1,227.0,40,125.0,90.0,0,0.0,23.62,0,...,1,1,1,0,0,0,1,0,1,785
19,70948,1,175.0,61,134.0,82.5,1,5.0,18.59,0,...,0,0,0,0,0,0,1,1,1,1451

In [4]:
df.columns

Index(['RANDID', 'SEX', 'TOTCHOL', 'AGE', 'SYSBP', 'DIABP', 'CURSMOKE',
       'CIGPDAY', 'BMI', 'DIABETES', 'BPMEDS', 'HEARTRTE', 'GLUCOSE', 'PREVMI',
       'PREVCHD', 'PREVAP', 'PREVSTRK', 'PREVHYP', 'TIME', 'PERIOD', 'DEATH',
       'HYPERTEN', 'TIMEHYP'],
      dtype='object')

In [5]:
hyp_df = df[['SEX', 'TOTCHOL', 'AGE', 'SYSBP', 'DIABP', 'CURSMOKE', 'CIGPDAY', 'BMI', 'DIABETES',
                 'BPMEDS', 'HEARTRTE', 'GLUCOSE', 'PREVCHD', 'PREVAP', 'PREVMI', 'PREVSTRK', 'PREVHYP', 'HYPERTEN']]
hyp_df

,SEX,TOTCHOL,AGE,SYSBP,DIABP,CURSMOKE,CIGPDAY,BMI,DIABETES,BPMEDS,HEARTRTE,GLUCOSE,PREVCHD,PREVAP,PREVMI,PREVSTRK,PREVHYP,HYPERTEN
0,1,195.0,39,106.0,70.0,0,0.0,26.97,0,0.0,80.0,77.0,0,0,0,0,0,0
1,2,250.0,46,121.0,81.0,0,0.0,28.73,0,0.0,95.0,76.0,0,0,0,0,0,0
2,1,245.0,48,127.5,80.0,1,20.0,25.34,0,0.0,75.0,70.0,0,0,0,0,0,0
3,2,285.0,46,130.0,84.0,1,23.0,23.10,0,0.0,85.0,85.0,0,0,0,0,0,1
4,2,205.0,63,138.0,71.0,0,0.0,33.11,0,0.0,60.0,85.0,0,0,0,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2649,1,233.0,58,125.5,84.0,0,0.0,26.05,0,0.0,67.0,76.0,0,0,0,0,0,0
2650,1,187.0,43,129.5,88.0,1,20.0,25.62,0,0.0,80.0,75.0,0,0,0,0,0,0
2651,1,207.0,51,126.5,80.0,1,43.0,19.71,0,0.0,65.0,68.0,0,0,0,0,0,0
2652,2,269.0,52,133.5,83.0,0,0.0,21.47,0,0.0,80.0,107.0,0,0,0,0,0,1
2653,2,196.0,39,133.0,86.0,1,30.0,20.91,0,0.0,85.0,80.0,0,0,0,0,0,1

In [6]:
target = hyp_df['HYPERTEN']
target_names = ['negative', 'positive']

In [7]:
data = hyp_df.drop('HYPERTEN', axis=1)
feature_names = data.columns
data.head()

,SEX,TOTCHOL,AGE,SYSBP,DIABP,CURSMOKE,CIGPDAY,BMI,DIABETES,BPMEDS,HEARTRTE,GLUCOSE,PREVCHD,PREVAP,PREVMI,PREVSTRK,PREVHYP
0,1,195.0,39,106.0,70.0,0,0.0,26.97,0,0.0,80.0,77.0,0,0,0,0,0
1,2,250.0,46,121.0,81.0,0,0.0,28.73,0,0.0,95.0,76.0,0,0,0,0,0
2,1,245.0,48,127.5,80.0,1,20.0,25.34,0,0.0,75.0,70.0,0,0,0,0,0
3,2,285.0,46,130.0,84.0,1,23.0,23.10,0,0.0,85.0,85.0,0,0,0,0,0
4,2,205.0,63,138.0,71.0,0,0.0,33.11,0,0.0,60.0,85.0,0,0,0,0,0

In [8]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(data, target, random_state=49)

In [9]:
from sklearn.ensemble import RandomForestClassifier
rf = RandomForestClassifier(n_estimators=500, class_weight = 'balanced')
rf = rf.fit(X_train, y_train)

print(f'Training Data Score: {rf.score(X_train, y_train)}')
print(f'Testing Data Score: {rf.score(X_test, y_test)}')

Training Data Score: 1.0
Testing Data Score: 0.7033132530120482

In [10]:
importances = rf.feature_importances_
importances

array([0.02003844, 0.12137487, 0.10040715, 0.18950024, 0.14426373,
       0.01175558, 0.0506757 , 0.14169805, 0.00239961, 0.        ,
       0.10011859, 0.1081729 , 0.00353967, 0.00298993, 0.00185536,
       0.00121019, 0.        ])

In [11]:
sorted(zip(rf.feature_importances_, feature_names), reverse=True)

[(0.18950023808291686, 'SYSBP'),
 (0.14426372969317114, 'DIABP'),
 (0.14169805162578503, 'BMI'),
 (0.1213748679064381, 'TOTCHOL'),
 (0.10817290031817454, 'GLUCOSE'),
 (0.10040715257841785, 'AGE'),
 (0.10011858643361687, 'HEARTRTE'),
 (0.05067569778149507, 'CIGPDAY'),
 (0.020038438564291997, 'SEX'),
 (0.011755579918508424, 'CURSMOKE'),
 (0.0035396710308890256, 'PREVCHD'),
 (0.0029899343240269703, 'PREVAP'),
 (0.002399605378180715, 'DIABETES'),
 (0.0018553610427474467, 'PREVMI'),
 (0.0012101853213400534, 'PREVSTRK'),
 (0.0, 'PREVHYP'),
 (0.0, 'BPMEDS')]

In [14]:
predictions  = rf.predict(X_test)
hyp_predictions = pd.DataFrame({'Prediction': predictions, 'Actual': y_test}).reset_index(drop=True)
hyp_predictions

     Prediction  Actual
0             1       1
1             1       0
2             0       1
3             1       1
4             1       1
..          ...     ...
659           0       0
660           1       1
661           1       0
662           1       1
663           0       0

[664 rows x 2 columns]

In [15]:
p0a0 = hyp_predictions.loc[(hyp_predictions['Prediction']==0) & (hyp_predictions['Actual']==0)]
p1a1 = hyp_predictions.loc[(hyp_predictions['Prediction']==1) & (hyp_predictions['Actual']==1)]
p0a1 = hyp_predictions.loc[(hyp_predictions['Prediction']==0) & (hyp_predictions['Actual']==1)]
p1a0 = hyp_predictions.loc[(hyp_predictions['Prediction']==1) & (hyp_predictions['Actual']==0)]

print(f'Event prediction and actual = 0: {len(p0a0)}')
print(f'Event prediction and actual = 1: {len(p1a1)}')
print(f'Event prediction = 0 and actual = 1: {len(p0a1)}')
print(f'Event prediction = 1 and actual = 0: {len(p1a0)}')

Event prediction and actual = 0: 138
Event prediction and actual = 1: 329
Event prediction = 0 and actual = 1: 77
Event prediction = 1 and actual = 0: 120