# Angina - Random Forest

In [1]:
from sklearn import tree
import pandas as pd

In [2]:
#read in data set
df = pd.read_csv("../../Resources/ANG_final_data.csv")
df.head(20)

,RANDID,SEX,TOTCHOL,AGE,SYSBP,DIABP,CURSMOKE,CIGPDAY,BMI,DIABETES,...,PREVMI,PREVCHD,PREVAP,PREVSTRK,PREVHYP,TIME,PERIOD,DEATH,ANGINA,TIMEAP
0,2448,1,195.0,39,106.0,70.0,0,0.0,26.97,0,...,0,0,0,0,0,0,1,0,0,8766
1,6238,2,250.0,46,121.0,81.0,0,0.0,28.73,0,...,0,0,0,0,0,0,1,0,0,8766
2,9428,1,245.0,48,127.5,80.0,1,20.0,25.34,0,...,0,0,0,0,0,0,1,0,0,8766
3,10552,2,225.0,61,150.0,95.0,1,30.0,28.58,0,...,0,0,0,0,1,0,1,1,0,2956
4,11252,2,285.0,46,130.0,84.0,1,23.0,23.10,0,...,0,0,0,0,0,0,1,0,0,8766
5,11263,2,228.0,43,180.0,110.0,0,0.0,30.30,0,...,0,0,0,0,1,0,1,0,0,8766
6,12629,2,205.0,63,138.0,71.0,0,0.0,33.11,0,...,0,0,0,0,0,0,1,0,1,373
7,12806,2,313.0,45,100.0,71.0,1,20.0,21.68,0,...,0,0,0,0,0,0,1,0,0,8766
8,14367,1,260.0,52,141.5,89.0,0,0.0,26.36,0,...,0,0,0,0,1,0,1,0,0,8766
9,16365,1,225.0,43,162.0,107.0,1,30.0,23.61,0,...,0,0,0,0,1,0,1,0,0,8766
10,16799,2,254.0,50,133.0,76.0,0,0.0,22.91,0,...,0,0,0,0,0,0,1,0,0,8766
11,19304,2,247.0,43,131.0,88.0,0,0.0,27.64,0,...,0,0,0,0,0,0,1,0,0,8766
12,20375,1,294.0,46,142.0,94.0,1,15.0,26.31,0,...,0,0,0,0,1,0,1,0,0,8766
13,23727,2,332.0,41,124.0,88.0,0,0.0,31.31,0,...,0,0,0,0,1,0,1,1,0,5592
14,30928,2,221.0,38,140.0,90.0,1,20.0,21.35,0,...,0,0,0,0,1,0,1,1,0,146
15,33077,1,232.0,48,138.0,90.0,1,10.0,22.37,0,...,0,0,0,0,1,0,1,0,0,8766
16,33555,2,291.0,46,112.0,78.0,1,20.0,23.38,0,...,0,0,0,0,0,0,1,1,0,1442
17,34689,2,195.0,38,122.0,84.5,1,5.0,23.24,0,...,0,0,0,0,0,0,1,0,0,8766
18,36459,1,195.0,41,139.0,88.0,0,0.0,26.88,0,...,0,0,0,0,0,0,1,0,0,8766
19,40435,2,190.0,42,108.0,70.5,1,30.0,21.59,0,...,0,0,0,0,0,0,1,0,0,8766

In [3]:
df.columns

Index(['RANDID', 'SEX', 'TOTCHOL', 'AGE', 'SYSBP', 'DIABP', 'CURSMOKE',
       'CIGPDAY', 'BMI', 'DIABETES', 'BPMEDS', 'HEARTRTE', 'GLUCOSE', 'PREVMI',
       'PREVCHD', 'PREVAP', 'PREVSTRK', 'PREVHYP', 'TIME', 'PERIOD', 'DEATH',
       'ANGINA', 'TIMEAP'],
      dtype='object')

In [4]:
ang_df = df.set_index('RANDID')
#Remove columns not involved in analysis
ang_df = ang_df[['SEX', 'TOTCHOL', 'AGE', 'SYSBP', 'DIABP', 'CURSMOKE',
       'CIGPDAY', 'BMI', 'DIABETES', 'BPMEDS', 'HEARTRTE', 'GLUCOSE', 'PREVMI',
       'PREVCHD', 'PREVSTRK', 'PREVHYP','ANGINA']]
ang_df.head()

,SEX,TOTCHOL,AGE,SYSBP,DIABP,CURSMOKE,CIGPDAY,BMI,DIABETES,BPMEDS,HEARTRTE,GLUCOSE,PREVMI,PREVCHD,PREVSTRK,PREVHYP,ANGINA
RANDID,,,,,,,,,,,,,,,,,
2448,1,195.0,39,106.0,70.0,0,0.0,26.97,0,0.0,80.0,77.0,0,0,0,0,0
6238,2,250.0,46,121.0,81.0,0,0.0,28.73,0,0.0,95.0,76.0,0,0,0,0,0
9428,1,245.0,48,127.5,80.0,1,20.0,25.34,0,0.0,75.0,70.0,0,0,0,0,0
10552,2,225.0,61,150.0,95.0,1,30.0,28.58,0,0.0,65.0,103.0,0,0,0,1,0
11252,2,285.0,46,130.0,84.0,1,23.0,23.10,0,0.0,85.0,85.0,0,0,0,0,0

In [5]:
target = ang_df["ANGINA"]
target_names = ["negative", "positive"]

In [6]:
data = ang_df.drop("ANGINA",axis=1)
feature_names = data.columns
data.head()

,SEX,TOTCHOL,AGE,SYSBP,DIABP,CURSMOKE,CIGPDAY,BMI,DIABETES,BPMEDS,HEARTRTE,GLUCOSE,PREVMI,PREVCHD,PREVSTRK,PREVHYP
RANDID,,,,,,,,,,,,,,,,
2448,1,195.0,39,106.0,70.0,0,0.0,26.97,0,0.0,80.0,77.0,0,0,0,0
6238,2,250.0,46,121.0,81.0,0,0.0,28.73,0,0.0,95.0,76.0,0,0,0,0
9428,1,245.0,48,127.5,80.0,1,20.0,25.34,0,0.0,75.0,70.0,0,0,0,0
10552,2,225.0,61,150.0,95.0,1,30.0,28.58,0,0.0,65.0,103.0,0,0,0,1
11252,2,285.0,46,130.0,84.0,1,23.0,23.10,0,0.0,85.0,85.0,0,0,0,0

In [7]:
# Split the data using train_test_split
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(data, target, random_state=49)

In [8]:
from sklearn.ensemble import RandomForestClassifier
# Create, fit, and score a Random Forest Classifier
rf = RandomForestClassifier(n_estimators=500, class_weight = "balanced")
rf = rf.fit(X_train, y_train)

print(f"Training Data Score: {rf.score(X_train, y_train)}")
print(f"Testing Data Score: {rf.score(X_test, y_test)}")

Training Data Score: 1.0
Testing Data Score: 0.8714436248682824

In [9]:
# calculate feature importance
importances = rf.feature_importances_
importances

array([0.02424087, 0.16363345, 0.10666273, 0.12973842, 0.11587949,
       0.01189983, 0.0472073 , 0.15210175, 0.00387719, 0.00625833,
       0.10240035, 0.11665284, 0.00208853, 0.00259231, 0.0013524 ,
       0.0134142 ])

In [10]:
# sort the features by their importance
sorted(zip(rf.feature_importances_, feature_names), reverse=True)

[(0.16363344743250963, 'TOTCHOL'),
 (0.1521017482883188, 'BMI'),
 (0.12973842337537997, 'SYSBP'),
 (0.11665284294867019, 'GLUCOSE'),
 (0.11587949390556444, 'DIABP'),
 (0.10666272928209516, 'AGE'),
 (0.10240034976725185, 'HEARTRTE'),
 (0.04720730383800393, 'CIGPDAY'),
 (0.02424086750487673, 'SEX'),
 (0.013414201980823994, 'PREVHYP'),
 (0.011899827804722714, 'CURSMOKE'),
 (0.006258331289274519, 'BPMEDS'),
 (0.0038771891624694295, 'DIABETES'),
 (0.002592310827956042, 'PREVCHD'),
 (0.002088528362773184, 'PREVMI'),
 (0.0013524042293094974, 'PREVSTRK')]

In [14]:
#Make predictions (0 = no event occurred, 1 = event occurred)
predictions = rf.predict(X_test)
ang_predictions = pd.DataFrame({"Prediction": predictions, "Actual": y_test}).reset_index(drop=True)
ang_predictions

     Prediction  Actual
0             0       1
1             0       0
2             0       0
3             0       0
4             0       0
..          ...     ...
944           0       0
945           0       1
946           0       0
947           0       0
948           0       0

[949 rows x 2 columns]

In [12]:
# Calculate classification report
from sklearn.metrics import classification_report
print(classification_report(y_test, predictions,
                            target_names=target_names))

              precision    recall  f1-score   support

    negative       0.87      1.00      0.93       827
    positive       0.00      0.00      0.00       122

    accuracy                           0.87       949
   macro avg       0.44      0.50      0.47       949
weighted avg       0.76      0.87      0.81       949

C:\Users\jtaum\Anaconda3\envs\PythonAdv\lib\site-packages\sklearn\metrics\_classification.py:1221: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

In [15]:
p0a0 = ang_predictions.loc[(ang_predictions['Prediction']==0) & (ang_predictions['Actual']==0)]
p1a1 = ang_predictions.loc[(ang_predictions['Prediction']==1) & (ang_predictions['Actual']==1)]
p0a1 = ang_predictions.loc[(ang_predictions['Prediction']==0) & (ang_predictions['Actual']==1)]
p1a0 = ang_predictions.loc[(ang_predictions['Prediction']==1) & (ang_predictions['Actual']==0)]

In [16]:
print(f"Event prediction and actual = 0:  {len(p0a0)}")
print(f"Event prediction and actual = 1:  {len(p1a1)}")
print(f"Event prediction = 0 and actual = 1:  {len(p0a1)}")
print(f"Event prediction = 1 and actual = 0:  {len(p1a0)}")

Event prediction and actual = 0:  827
Event prediction and actual = 1:  0
Event prediction = 0 and actual = 1:  122
Event prediction = 1 and actual = 0:  0

In [ ]:
TP = len(p1a1)
TN = len(p0a0)
FP = len(p1a0)
FN = len(p0a1)

Accuracy = (TP + TN)/len(cvd_predictions)
Precision = TP/(TP + FP)
Recall = TP/(TP + FN)
F1 = 2*((Precision*Recall)/ (Precision+Recall))

print("Accuracy: %.3f" % Accuracy)
print("Precision: %.3f" % Precision)
print("Recall: %.3f" % Recall)
print("F1 Measure: %.3f" % F1)

## Separate by gender

In [ ]:
#filter df by gender (males = 1, females = 2)
male_mi_fchd = mi_fchd_df.loc[(mi_fchd_df["SEX"] ==1)]
female_mi_fchd = mi_fchd_df.loc[(mi_fchd_df["SEX"] ==2)]

In [ ]:
male_mi_fchd_df = male_mi_fchd.drop('SEX', axis=1)
female_mi_fchd_df = female_mi_fchd.drop('SEX', axis=1)

In [ ]:
female_mi_fchd_df

In [ ]:
male_target = male_mi_fchd_df["MI_FCHD"]
male_target_names = ["negative", "positive"]

female_target = female_mi_fchd_df["MI_FCHD"]
female_target_names = ["negative", "positive"]

In [ ]:
male_data = male_mi_fchd_df.drop("MI_FCHD",axis=1)
male_feature_names = male_data.columns

female_data = female_mi_fchd_df.drop("MI_FCHD", axis=1)
female_feature_names = female_data.columns

In [ ]:
# Split the data using train_test_split - males
from sklearn.model_selection import train_test_split

mX_train, mX_test, my_train, my_test = train_test_split(male_data, male_target, random_state=49)

In [ ]:
# Create, fit, and score a Random Forest Classifier - males
mrf = RandomForestClassifier(n_estimators=500, class_weight = "balanced")
mrf = mrf.fit(mX_train, my_train)

print(f"Training Data Score (males): {mrf.score(mX_train, my_train)}")
print(f"Testing Data Score (males): {mrf.score(mX_test, my_test)}")

In [ ]:
# sort the features by their importance
sorted(zip(mrf.feature_importances_, male_feature_names), reverse=True)

In [ ]:
# Calculate classification report
from sklearn.metrics import classification_report
print(classification_report(my_test, predictions,
                            target_names=target_names))

In [ ]:
#Make predictions (0 = no event occurred, 1 = event occurred)
m_predictions = mrf.predict(mX_test)
m_mi_fchd_predictions = pd.DataFrame({"Prediction": m_predictions, "Actual": my_test}).reset_index(drop=True)

mp0a0 = m_mi_fchd_predictions.loc[(m_mi_fchd_predictions['Prediction']==0) & (m_mi_fchd_predictions['Actual']==0)]
mp1a1 = m_mi_fchd_predictions.loc[(m_mi_fchd_predictions['Prediction']==1) & (m_mi_fchd_predictions['Actual']==1)]
mp0a1 = m_mi_fchd_predictions.loc[(m_mi_fchd_predictions['Prediction']==0) & (m_mi_fchd_predictions['Actual']==1)]
mp1a0 = m_mi_fchd_predictions.loc[(m_mi_fchd_predictions['Prediction']==1) & (m_mi_fchd_predictions['Actual']==0)]

print(f"Event prediction and actual = 0 (male):  {len(mp0a0)}")
print(f"Event prediction and actual = 1 (male):  {len(mp1a1)}")
print(f"Event prediction = 0 and actual = 1 (male):  {len(mp0a1)}")
print(f"Event prediction = 1 and actual = 0 (male):  {len(mp1a0)}")

In [ ]:
# Calculate classification report
from sklearn.metrics import classification_report
print(classification_report(my_test, m_predictions,
                            target_names=male_target_names))

In [ ]:
# Split the data using train_test_split - females

fX_train, fX_test, fy_train, fy_test = train_test_split(female_data, female_target, random_state=49)

In [ ]:
# Create, fit, and score a Random Forest Classifier - females
frf = RandomForestClassifier(n_estimators=500, class_weight = "balanced")
frf = frf.fit(fX_train, fy_train)

print(f"Training Data Score (females): {frf.score(fX_train, fy_train)}")
print(f"Testing Data Score (females): {frf.score(fX_test, fy_test)}")

In [ ]:
# sort the features by their importance
sorted(zip(frf.feature_importances_, female_feature_names), reverse=True)

In [ ]:
#Make predictions (0 = no event occurred, 1 = event occurred)
f_predictions = frf.predict(fX_test)
f_mi_fchd_predictions = pd.DataFrame({"Prediction": f_predictions, "Actual": fy_test}).reset_index(drop=True)

fp0a0 = f_mi_fchd_predictions.loc[(f_mi_fchd_predictions['Prediction']==0) & (f_mi_fchd_predictions['Actual']==0)]
fp1a1 = f_mi_fchd_predictions.loc[(f_mi_fchd_predictions['Prediction']==1) & (f_mi_fchd_predictions['Actual']==1)]
fp0a1 = f_mi_fchd_predictions.loc[(f_mi_fchd_predictions['Prediction']==0) & (f_mi_fchd_predictions['Actual']==1)]
fp1a0 = f_mi_fchd_predictions.loc[(f_mi_fchd_predictions['Prediction']==1) & (f_mi_fchd_predictions['Actual']==0)]

print(f"Event prediction and actual = 0 (female):  {len(fp0a0)}")
print(f"Event prediction and actual = 1 (female):  {len(fp1a1)}")
print(f"Event prediction = 0 and actual = 1 (female):  {len(fp0a1)}")
print(f"Event prediction = 1 and actual = 0 (female):  {len(fp1a0)}")

In [ ]:
# Calculate classification report
from sklearn.metrics import classification_report
print(classification_report(fy_test, f_predictions,
                            target_names=female_target_names))