In [1]:
# ANG - Random Forest - Period 1

In [2]:
from sklearn import tree
import pandas as pd

In [4]:
#read in data set
df = pd.read_csv("../../Resources/ANG_final_data.csv")
df.head(20)

,RANDID,SEX,TOTCHOL,AGE,SYSBP,DIABP,CURSMOKE,CIGPDAY,BMI,DIABETES,...,PREVMI,PREVCHD,PREVAP,PREVSTRK,PREVHYP,TIME,PERIOD,DEATH,ANGINA,TIMEAP
0,2448,1,195.0,39,106.0,70.0,0,0.0,26.97,0,...,0,0,0,0,0,0,1,0,0,8766
1,6238,2,250.0,46,121.0,81.0,0,0.0,28.73,0,...,0,0,0,0,0,0,1,0,0,8766
2,9428,1,245.0,48,127.5,80.0,1,20.0,25.34,0,...,0,0,0,0,0,0,1,0,0,8766
3,10552,2,225.0,61,150.0,95.0,1,30.0,28.58,0,...,0,0,0,0,1,0,1,1,0,2956
4,11252,2,285.0,46,130.0,84.0,1,23.0,23.10,0,...,0,0,0,0,0,0,1,0,0,8766
5,11263,2,228.0,43,180.0,110.0,0,0.0,30.30,0,...,0,0,0,0,1,0,1,0,0,8766
6,12629,2,205.0,63,138.0,71.0,0,0.0,33.11,0,...,0,0,0,0,0,0,1,0,1,373
7,12806,2,313.0,45,100.0,71.0,1,20.0,21.68,0,...,0,0,0,0,0,0,1,0,0,8766
8,14367,1,260.0,52,141.5,89.0,0,0.0,26.36,0,...,0,0,0,0,1,0,1,0,0,8766
9,16365,1,225.0,43,162.0,107.0,1,30.0,23.61,0,...,0,0,0,0,1,0,1,0,0,8766
10,16799,2,254.0,50,133.0,76.0,0,0.0,22.91,0,...,0,0,0,0,0,0,1,0,0,8766
11,19304,2,247.0,43,131.0,88.0,0,0.0,27.64,0,...,0,0,0,0,0,0,1,0,0,8766
12,20375,1,294.0,46,142.0,94.0,1,15.0,26.31,0,...,0,0,0,0,1,0,1,0,0,8766
13,23727,2,332.0,41,124.0,88.0,0,0.0,31.31,0,...,0,0,0,0,1,0,1,1,0,5592
14,30928,2,221.0,38,140.0,90.0,1,20.0,21.35,0,...,0,0,0,0,1,0,1,1,0,146
15,33077,1,232.0,48,138.0,90.0,1,10.0,22.37,0,...,0,0,0,0,1,0,1,0,0,8766
16,33555,2,291.0,46,112.0,78.0,1,20.0,23.38,0,...,0,0,0,0,0,0,1,1,0,1442
17,34689,2,195.0,38,122.0,84.5,1,5.0,23.24,0,...,0,0,0,0,0,0,1,0,0,8766
18,36459,1,195.0,41,139.0,88.0,0,0.0,26.88,0,...,0,0,0,0,0,0,1,0,0,8766
19,40435,2,190.0,42,108.0,70.5,1,30.0,21.59,0,...,0,0,0,0,0,0,1,0,0,8766

In [5]:
df.columns

Index(['RANDID', 'SEX', 'TOTCHOL', 'AGE', 'SYSBP', 'DIABP', 'CURSMOKE',
       'CIGPDAY', 'BMI', 'DIABETES', 'BPMEDS', 'HEARTRTE', 'GLUCOSE', 'PREVMI',
       'PREVCHD', 'PREVAP', 'PREVSTRK', 'PREVHYP', 'TIME', 'PERIOD', 'DEATH',
       'ANGINA', 'TIMEAP'],
      dtype='object')

In [6]:
ang_df = df.set_index('RANDID')

ang_df = ang_df[['SEX', 'TOTCHOL', 'AGE', 'SYSBP', 'DIABP', 'CURSMOKE', 'CIGPDAY', 'BMI', 'DIABETES',
                'BPMEDS', 'HEARTRTE', 'GLUCOSE', 'PREVMI', 'PREVCHD', 'PREVSTRK', 'PREVHYP', 'ANGINA']]
ang_df

,SEX,TOTCHOL,AGE,SYSBP,DIABP,CURSMOKE,CIGPDAY,BMI,DIABETES,BPMEDS,HEARTRTE,GLUCOSE,PREVMI,PREVCHD,PREVSTRK,PREVHYP,ANGINA
RANDID,,,,,,,,,,,,,,,,,
2448,1,195.0,39,106.0,70.0,0,0.0,26.97,0,0.0,80.0,77.0,0,0,0,0,0
6238,2,250.0,46,121.0,81.0,0,0.0,28.73,0,0.0,95.0,76.0,0,0,0,0,0
9428,1,245.0,48,127.5,80.0,1,20.0,25.34,0,0.0,75.0,70.0,0,0,0,0,0
10552,2,225.0,61,150.0,95.0,1,30.0,28.58,0,0.0,65.0,103.0,0,0,0,1,0
11252,2,285.0,46,130.0,84.0,1,23.0,23.10,0,0.0,85.0,85.0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9984683,1,313.0,50,179.0,92.0,1,1.0,25.97,0,0.0,66.0,86.0,0,0,0,1,1
9989287,1,207.0,51,126.5,80.0,1,43.0,19.71,0,0.0,65.0,68.0,0,0,0,0,0
9995546,2,269.0,52,133.5,83.0,0,0.0,21.47,0,0.0,80.0,107.0,0,0,0,0,1
9998212,1,185.0,40,141.0,98.0,0,0.0,25.60,0,0.0,67.0,72.0,0,0,0,1,0
9999312,2,196.0,39,133.0,86.0,1,30.0,20.91,0,0.0,85.0,80.0,0,0,0,0,0

In [7]:
target = ang_df['ANGINA']
target_names = ['negative', 'positive']

In [8]:
data = ang_df.drop('ANGINA', axis=1)
feature_names = data.columns
data.head()

,SEX,TOTCHOL,AGE,SYSBP,DIABP,CURSMOKE,CIGPDAY,BMI,DIABETES,BPMEDS,HEARTRTE,GLUCOSE,PREVMI,PREVCHD,PREVSTRK,PREVHYP
RANDID,,,,,,,,,,,,,,,,
2448,1,195.0,39,106.0,70.0,0,0.0,26.97,0,0.0,80.0,77.0,0,0,0,0
6238,2,250.0,46,121.0,81.0,0,0.0,28.73,0,0.0,95.0,76.0,0,0,0,0
9428,1,245.0,48,127.5,80.0,1,20.0,25.34,0,0.0,75.0,70.0,0,0,0,0
10552,2,225.0,61,150.0,95.0,1,30.0,28.58,0,0.0,65.0,103.0,0,0,0,1
11252,2,285.0,46,130.0,84.0,1,23.0,23.10,0,0.0,85.0,85.0,0,0,0,0

In [9]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(data, target, random_state=49)

In [10]:
from sklearn.ensemble import RandomForestClassifier

rf = RandomForestClassifier(n_estimators=500, class_weight = 'balanced')
rf = rf.fit(X_train, y_train)

print(f'Training Data Score: {rf.score(X_train, y_train)}')
print(f'Testing Data Score: {rf.score(X_test, y_test)}')

Training Data Score: 1.0
Testing Data Score: 0.8714436248682824

In [21]:
importances = rf.feature_importances_
importances

AttributeError: 'numpy.ndarray' object has no attribute 'plt'

In [20]:
#sorted(zip(rf.feature_importances_, feature_names), reverse=True)
feat_importances = (sorted(zip(rf.feature_importances_, feature_names), reverse=True)
feat_importances.plot(kind='barh')

SyntaxError: invalid syntax (<ipython-input-20-4cf9d9cffbc0>, line 3)

SyntaxError: invalid syntax (<ipython-input-15-e7db823ca65c>, line 2)

In [17]:
predictions = rf.predict(X_test)
ang_predictions = pd.DataFrame({'Prediction': predictions, 'Actual': y_test}).reset_index(drop=True)
ang_predictions

     Prediction  Actual
0             0       1
1             0       0
2             0       0
3             0       0
4             0       0
..          ...     ...
944           0       0
945           0       1
946           0       0
947           0       0
948           0       0

[949 rows x 2 columns]

In [18]:
p0a0 = ang_predictions.loc[(ang_predictions['Prediction']==0) & (ang_predictions['Actual']==0)]
p1a1 = ang_predictions.loc[(ang_predictions['Prediction']==1) & (ang_predictions['Actual']==1)]
p0a1 = ang_predictions.loc[(ang_predictions['Prediction']==0) & (ang_predictions['Actual']==1)]
p1a0 = ang_predictions.loc[(ang_predictions['Prediction']==1) & (ang_predictions['Actual']==0)]

print(f'Event prediction and actual = 0: {len(p0a0)}')
print(f'Event prediction and actual = 1: {len(p1a1)}')
print(f'Event prediction = 0 and actual = 1: {len(p0a1)}')
print(f'Event prediction = 1 and actual = 0: {len(p1a0)}')

Event prediction and actual = 0: 827
Event prediction and actual = 1: 0
Event prediction = 0 and actual = 1: 122
Event prediction = 1 and actual = 0: 0