# CVD - Random Forest - Period 3

In [1]:
from sklearn import tree
import pandas as pd

In [2]:
#read in data set
df = pd.read_csv("Resources/cvd_period3_data.csv")
df.head(20)

,RANDID,SEX,TOTCHOL,AGE,SYSBP,DIABP,CURSMOKE,CIGPDAY,BMI,DIABETES,BPMEDS,HEARTRTE,GLUCOSE,PREVAP,PREVHYP,HDLC,LDLC,DEATH,CVD
0,6238,2,237.0,58,108.0,66.0,0,0.0,28.50,0,0.0,80.0,71.0,0,0,54.0,141.0,0,0
1,11263,2,220.0,55,180.0,106.0,0,0.0,31.17,1,1.0,86.0,81.0,0,1,46.0,135.0,0,1
2,12806,2,320.0,57,110.0,46.0,1,30.0,22.02,0,0.0,75.0,87.0,0,0,34.0,286.0,0,0
3,14367,1,280.0,64,168.0,100.0,0,0.0,25.72,0,0.0,92.0,82.0,0,1,44.0,236.0,0,0
4,16365,1,211.0,55,173.0,123.0,0,0.0,29.11,0,1.0,75.0,85.0,0,1,48.0,163.0,0,0
5,23727,2,159.0,53,124.0,78.0,0,0.0,26.62,0,0.0,68.0,135.0,0,1,53.0,106.0,1,0
6,24721,2,264.0,51,141.0,81.0,1,15.0,24.77,0,0.0,85.0,97.0,0,1,58.0,206.0,1,0
7,33077,1,215.0,60,144.5,80.0,1,10.0,22.96,0,0.0,57.0,91.0,0,1,62.0,135.0,0,0
8,34689,2,212.0,49,163.0,96.0,1,10.0,31.45,0,0.0,82.0,84.0,0,1,40.0,172.0,0,0
9,36459,1,162.0,53,152.5,101.0,0,0.0,26.43,0,0.0,105.0,78.0,0,1,31.0,91.0,0,0
10,40435,2,226.0,54,126.0,75.0,1,40.0,21.59,0,0.0,85.0,102.0,0,0,84.0,142.0,0,0
11,43770,2,283.0,64,159.0,69.0,0,0.0,32.93,1,0.0,70.0,230.0,0,1,45.0,238.0,1,1
12,45464,2,236.0,64,150.0,89.0,1,20.0,24.01,0,0.0,90.0,80.0,0,1,93.0,143.0,0,0
13,47561,1,290.0,56,132.0,70.0,1,40.0,22.73,0,0.0,100.0,90.0,0,1,54.0,236.0,0,0
14,55965,2,298.0,72,109.0,60.0,0,0.0,26.20,0,0.0,80.0,100.0,0,0,38.0,260.0,0,0
15,63156,1,240.0,47,131.0,90.0,0,0.0,26.77,0,0.0,70.0,76.0,0,1,40.0,200.0,0,0
16,66472,2,249.0,72,157.0,87.0,0,0.0,29.55,1,0.0,65.0,73.0,0,1,78.0,171.0,1,1
17,67905,1,300.0,48,125.0,83.0,0,0.0,34.34,0,0.0,58.0,96.0,0,1,47.0,253.0,0,0
18,68194,1,206.0,55,129.0,85.0,1,50.0,26.40,0,0.0,84.0,69.0,0,0,47.0,159.0,0,0
19,82188,1,226.0,49,190.0,123.0,0,0.0,45.43,0,1.0,100.0,73.0,0,1,34.0,192.0,0,0

In [3]:
df.columns

Index(['RANDID', 'SEX', 'TOTCHOL', 'AGE', 'SYSBP', 'DIABP', 'CURSMOKE',
       'CIGPDAY', 'BMI', 'DIABETES', 'BPMEDS', 'HEARTRTE', 'GLUCOSE', 'PREVAP',
       'PREVHYP', 'HDLC', 'LDLC', 'DEATH', 'CVD'],
      dtype='object')

In [4]:
cvd_df = df.set_index('RANDID')
#Remove columns not involved in analysis
#removed 'Time', 'Period', 'Death', 'MI_FCHD', 'TIMEMI', 'TIMEMIFC'
cvd_df = cvd_df[['SEX', 'TOTCHOL', 'AGE', 'SYSBP', 'DIABP', 'CURSMOKE',
       'CIGPDAY', 'BMI', 'DIABETES', 'BPMEDS', 'HEARTRTE', 'GLUCOSE', 'PREVAP',
       'PREVHYP', 'HDLC', 'LDLC', 'CVD']]
cvd_df.head()

,SEX,TOTCHOL,AGE,SYSBP,DIABP,CURSMOKE,CIGPDAY,BMI,DIABETES,BPMEDS,HEARTRTE,GLUCOSE,PREVAP,PREVHYP,HDLC,LDLC,CVD
RANDID,,,,,,,,,,,,,,,,,
6238,2,237.0,58,108.0,66.0,0,0.0,28.50,0,0.0,80.0,71.0,0,0,54.0,141.0,0
11263,2,220.0,55,180.0,106.0,0,0.0,31.17,1,1.0,86.0,81.0,0,1,46.0,135.0,1
12806,2,320.0,57,110.0,46.0,1,30.0,22.02,0,0.0,75.0,87.0,0,0,34.0,286.0,0
14367,1,280.0,64,168.0,100.0,0,0.0,25.72,0,0.0,92.0,82.0,0,1,44.0,236.0,0
16365,1,211.0,55,173.0,123.0,0,0.0,29.11,0,1.0,75.0,85.0,0,1,48.0,163.0,0

In [5]:
target = cvd_df["CVD"]
target_names = ["No_CVD", "CVD"]

In [6]:
data = cvd_df.drop("CVD",axis=1)
feature_names = data.columns
data.head()

,SEX,TOTCHOL,AGE,SYSBP,DIABP,CURSMOKE,CIGPDAY,BMI,DIABETES,BPMEDS,HEARTRTE,GLUCOSE,PREVAP,PREVHYP,HDLC,LDLC
RANDID,,,,,,,,,,,,,,,,
6238,2,237.0,58,108.0,66.0,0,0.0,28.50,0,0.0,80.0,71.0,0,0,54.0,141.0
11263,2,220.0,55,180.0,106.0,0,0.0,31.17,1,1.0,86.0,81.0,0,1,46.0,135.0
12806,2,320.0,57,110.0,46.0,1,30.0,22.02,0,0.0,75.0,87.0,0,0,34.0,286.0
14367,1,280.0,64,168.0,100.0,0,0.0,25.72,0,0.0,92.0,82.0,0,1,44.0,236.0
16365,1,211.0,55,173.0,123.0,0,0.0,29.11,0,1.0,75.0,85.0,0,1,48.0,163.0

In [7]:
# Split the data using train_test_split
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(data, target, random_state=49)

In [8]:
from sklearn.ensemble import RandomForestClassifier
# Create, fit, and score a Random Forest Classifier
rf = RandomForestClassifier(n_estimators=500, class_weight = "balanced")
rf = rf.fit(X_train, y_train)

print(f"Training Data Score: {rf.score(X_train, y_train)}")
print(f"Testing Data Score: {rf.score(X_test, y_test)}")

Training Data Score: 1.0
Testing Data Score: 0.8481262327416174

In [9]:
# sort the features by their importance
sorted(zip(rf.feature_importances_, feature_names), reverse=True)

[(0.1309491079366102, 'SYSBP'),
 (0.1170849737013892, 'AGE'),
 (0.09755592364707474, 'BMI'),
 (0.09736619516678371, 'HDLC'),
 (0.08918065447632642, 'LDLC'),
 (0.08476936035873103, 'TOTCHOL'),
 (0.08361031035486888, 'GLUCOSE'),
 (0.08346216198415879, 'DIABP'),
 (0.07666857352560076, 'HEARTRTE'),
 (0.036043167010420124, 'SEX'),
 (0.03385776396396639, 'CIGPDAY'),
 (0.03302780252085095, 'PREVHYP'),
 (0.014062059533105376, 'DIABETES'),
 (0.011948901740119321, 'BPMEDS'),
 (0.010413044079994209, 'CURSMOKE'),
 (0.0, 'PREVAP')]

In [10]:
#Make predictions (0 = no event occurred, 1 = event occurred)
predictions = rf.predict(X_test)
cvd_predictions = pd.DataFrame({"Prediction": predictions, "Actual": y_test}).reset_index(drop=True)
cvd_predictions

     Prediction  Actual
0             1       1
1             0       0
2             0       1
3             0       0
4             0       0
..          ...     ...
502           0       0
503           0       0
504           0       1
505           0       0
506           0       0

[507 rows x 2 columns]

In [11]:
p0a0 = cvd_predictions.loc[(cvd_predictions['Prediction']==0) & (cvd_predictions['Actual']==0)]
p1a1 = cvd_predictions.loc[(cvd_predictions['Prediction']==1) & (cvd_predictions['Actual']==1)]
p0a1 = cvd_predictions.loc[(cvd_predictions['Prediction']==0) & (cvd_predictions['Actual']==1)]
p1a0 = cvd_predictions.loc[(cvd_predictions['Prediction']==1) & (cvd_predictions['Actual']==0)]

print(f"Event prediction = 0 and actual = 0:  {len(p0a0)}")
print(f"Event prediction = 1 and actual = 1:  {len(p1a1)}")
print(f"Event prediction = 0 and actual = 1:  {len(p0a1)}")
print(f"Event prediction = 1 and actual = 0:  {len(p1a0)}")

Event prediction = 0 and actual = 0:  427
Event prediction = 1 and actual = 1:  3
Event prediction = 0 and actual = 1:  73
Event prediction = 1 and actual = 0:  4

## Separate by gender

In [12]:
#filter df by gender (males = 1, females = 2)
male_cvd = cvd_df.loc[(cvd_df["SEX"] ==1)]
female_cvd = cvd_df.loc[(cvd_df["SEX"] ==2)]

In [13]:
male_cvd

,SEX,TOTCHOL,AGE,SYSBP,DIABP,CURSMOKE,CIGPDAY,BMI,DIABETES,BPMEDS,HEARTRTE,GLUCOSE,PREVAP,PREVHYP,HDLC,LDLC,CVD
RANDID,,,,,,,,,,,,,,,,,
14367,1,280.0,64,168.0,100.0,0,0.0,25.72,0,0.0,92.0,82.0,0,1,44.0,236.0,0
16365,1,211.0,55,173.0,123.0,0,0.0,29.11,0,1.0,75.0,85.0,0,1,48.0,163.0,0
33077,1,215.0,60,144.5,80.0,1,10.0,22.96,0,0.0,57.0,91.0,0,1,62.0,135.0,0
36459,1,162.0,53,152.5,101.0,0,0.0,26.43,0,0.0,105.0,78.0,0,1,31.0,91.0,0
47561,1,290.0,56,132.0,70.0,1,40.0,22.73,0,0.0,100.0,90.0,0,1,54.0,236.0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9938128,1,215.0,60,160.0,84.0,1,40.0,25.23,0,0.0,85.0,81.0,0,1,41.0,174.0,0
9949037,1,193.0,60,143.0,92.0,0,0.0,24.77,0,0.0,72.0,80.0,0,1,45.0,148.0,0
9961615,1,238.0,58,174.0,83.0,1,30.0,23.65,1,0.0,105.0,180.0,0,1,83.0,155.0,0
9982118,1,219.0,70,163.5,75.0,0,0.0,25.26,0,0.0,65.0,103.0,0,1,50.0,169.0,1
9998212,1,153.0,52,143.0,89.0,0,0.0,25.74,0,0.0,65.0,72.0,0,1,30.0,123.0,0

In [14]:
female_cvd

,SEX,TOTCHOL,AGE,SYSBP,DIABP,CURSMOKE,CIGPDAY,BMI,DIABETES,BPMEDS,HEARTRTE,GLUCOSE,PREVAP,PREVHYP,HDLC,LDLC,CVD
RANDID,,,,,,,,,,,,,,,,,
6238,2,237.0,58,108.0,66.0,0,0.0,28.50,0,0.0,80.0,71.0,0,0,54.0,141.0,0
11263,2,220.0,55,180.0,106.0,0,0.0,31.17,1,1.0,86.0,81.0,0,1,46.0,135.0,1
12806,2,320.0,57,110.0,46.0,1,30.0,22.02,0,0.0,75.0,87.0,0,0,34.0,286.0,0
23727,2,159.0,53,124.0,78.0,0,0.0,26.62,0,0.0,68.0,135.0,0,1,53.0,106.0,0
24721,2,264.0,51,141.0,81.0,1,15.0,24.77,0,0.0,85.0,97.0,0,1,58.0,206.0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9969773,2,229.0,62,188.0,91.0,0,0.0,34.74,1,1.0,85.0,68.0,0,1,43.0,186.0,1
9973350,2,267.0,63,160.0,88.0,0,0.0,25.60,1,0.0,82.0,71.0,0,1,65.0,202.0,0
9978986,2,243.0,68,110.0,66.0,0,0.0,24.30,0,0.0,80.0,108.0,0,1,65.0,178.0,0
9990894,2,228.0,60,205.0,100.0,1,20.0,22.37,0,0.0,80.0,91.0,0,1,47.0,181.0,0
9993179,2,251.0,56,145.0,92.0,1,35.0,21.97,0,1.0,95.0,90.0,0,1,70.0,181.0,0

In [15]:
male_cvd.columns

Index(['SEX', 'TOTCHOL', 'AGE', 'SYSBP', 'DIABP', 'CURSMOKE', 'CIGPDAY', 'BMI',
       'DIABETES', 'BPMEDS', 'HEARTRTE', 'GLUCOSE', 'PREVAP', 'PREVHYP',
       'HDLC', 'LDLC', 'CVD'],
      dtype='object')

In [16]:
male_cvd_df = male_cvd.drop('SEX', axis=1)
female_cvd_df = female_cvd.drop('SEX', axis=1)

In [17]:
male_target = male_cvd_df["CVD"]
male_target_names = ["No_CVD", "CVD"]

female_target = female_cvd_df["CVD"]
female_target_names = ["No_CVD", "CVD"]

In [18]:
male_data = male_cvd_df.drop("CVD",axis=1)
male_feature_names = male_data.columns

female_data = female_cvd_df.drop("CVD", axis=1)
female_feature_names = female_data.columns

In [19]:
# Split the data using train_test_split - males
from sklearn.model_selection import train_test_split

mX_train, mX_test, my_train, my_test = train_test_split(male_data, male_target, random_state=49)

In [20]:
# Create, fit, and score a Random Forest Classifier - males
mrf = RandomForestClassifier(n_estimators=500, class_weight = "balanced")
mrf = mrf.fit(mX_train, my_train)

print(f"Training Data Score (males): {mrf.score(mX_train, my_train)}")
print(f"Testing Data Score (males): {mrf.score(mX_test, my_test)}")

Training Data Score (males): 1.0
Testing Data Score (males): 0.7285714285714285

In [21]:
# sort the features by their importance
sorted(zip(mrf.feature_importances_, male_feature_names), reverse=True)

[(0.1264484921348023, 'AGE'),
 (0.11854434201887036, 'SYSBP'),
 (0.09945921001336998, 'LDLC'),
 (0.09778826912190311, 'BMI'),
 (0.09357977716000683, 'HDLC'),
 (0.09080885461703359, 'TOTCHOL'),
 (0.0894661891467767, 'GLUCOSE'),
 (0.08605704327196867, 'DIABP'),
 (0.08135225519201113, 'HEARTRTE'),
 (0.037569737213426824, 'CIGPDAY'),
 (0.03627820596310636, 'PREVHYP'),
 (0.017544691295602922, 'BPMEDS'),
 (0.014140568105491197, 'CURSMOKE'),
 (0.010962364745629928, 'DIABETES'),
 (0.0, 'PREVAP')]

In [22]:
#Make predictions (0 = no event occurred, 1 = event occurred)
m_predictions = mrf.predict(mX_test)
m_cvd_predictions = pd.DataFrame({"Prediction": m_predictions, "Actual": my_test}).reset_index(drop=True)

mp0a0 = m_cvd_predictions.loc[(m_cvd_predictions['Prediction']==0) & (m_cvd_predictions['Actual']==0)]
mp1a1 = m_cvd_predictions.loc[(m_cvd_predictions['Prediction']==1) & (m_cvd_predictions['Actual']==1)]
mp0a1 = m_cvd_predictions.loc[(m_cvd_predictions['Prediction']==0) & (m_cvd_predictions['Actual']==1)]
mp1a0 = m_cvd_predictions.loc[(m_cvd_predictions['Prediction']==1) & (m_cvd_predictions['Actual']==0)]

print(f"Event prediction and actual = 0 (male):  {len(mp0a0)}")
print(f"Event prediction and actual = 1 (male):  {len(mp1a1)}")
print(f"Event prediction = 0 and actual = 1 (male):  {len(mp0a1)}")
print(f"Event prediction = 1 and actual = 0 (male):  {len(mp1a0)}")

Event prediction and actual = 0 (male):  152
Event prediction and actual = 1 (male):  1
Event prediction = 0 and actual = 1 (male):  53
Event prediction = 1 and actual = 0 (male):  4

In [23]:
# Split the data using train_test_split - females

fX_train, fX_test, fy_train, fy_test = train_test_split(female_data, female_target, random_state=49)

In [24]:
# Create, fit, and score a Random Forest Classifier - females
frf = RandomForestClassifier(n_estimators=500, class_weight = "balanced")
frf = frf.fit(fX_train, fy_train)

print(f"Training Data Score (females): {frf.score(fX_train, fy_train)}")
print(f"Testing Data Score (females): {frf.score(fX_test, fy_test)}")

Training Data Score (females): 1.0
Testing Data Score (females): 0.9023569023569024

In [25]:
# sort the features by their importance
sorted(zip(frf.feature_importances_, female_feature_names), reverse=True)

[(0.12838245318238453, 'SYSBP'),
 (0.11740753155248554, 'AGE'),
 (0.10571225251315591, 'BMI'),
 (0.09674216760976227, 'DIABP'),
 (0.09467558484607828, 'HDLC'),
 (0.09436425212610772, 'LDLC'),
 (0.09069323081144702, 'GLUCOSE'),
 (0.08993373958908192, 'TOTCHOL'),
 (0.07696832107437197, 'HEARTRTE'),
 (0.03130934651098895, 'CIGPDAY'),
 (0.027065081476765646, 'PREVHYP'),
 (0.021139977128111876, 'DIABETES'),
 (0.014061968550864844, 'BPMEDS'),
 (0.011544093028393461, 'CURSMOKE'),
 (0.0, 'PREVAP')]

In [26]:
#Make predictions (0 = no event occurred, 1 = event occurred)
f_predictions = frf.predict(fX_test)
f_cvd_predictions = pd.DataFrame({"Prediction": f_predictions, "Actual": fy_test}).reset_index(drop=True)

fp0a0 = f_cvd_predictions.loc[(f_cvd_predictions['Prediction']==0) & (f_cvd_predictions['Actual']==0)]
fp1a1 = f_cvd_predictions.loc[(f_cvd_predictions['Prediction']==1) & (f_cvd_predictions['Actual']==1)]
fp0a1 = f_cvd_predictions.loc[(f_cvd_predictions['Prediction']==0) & (f_cvd_predictions['Actual']==1)]
fp1a0 = f_cvd_predictions.loc[(f_cvd_predictions['Prediction']==1) & (f_cvd_predictions['Actual']==0)]

print(f"Event prediction and actual = 0 (female):  {len(fp0a0)}")
print(f"Event prediction and actual = 1 (female):  {len(fp1a1)}")
print(f"Event prediction = 0 and actual = 1 (female):  {len(fp0a1)}")
print(f"Event prediction = 1 and actual = 0 (female):  {len(fp1a0)}")

Event prediction and actual = 0 (female):  268
Event prediction and actual = 1 (female):  0
Event prediction = 0 and actual = 1 (female):  28
Event prediction = 1 and actual = 0 (female):  1