# Death - Random Forest

In [1]:
from sklearn import tree
import pandas as pd

In [2]:
#read in data set
df = pd.read_csv("Resources/period1_final_data.csv")
df.head(20)

,RANDID,SEX,TOTCHOL,AGE,SYSBP,DIABP,CURSMOKE,CIGPDAY,BMI,DIABETES,...,CVD,HYPERTEN,TIMEAP,TIMEMI,TIMEMIFC,TIMECHD,TIMESTRK,TIMECVD,TIMEDTH,TIMEHYP
0,2448,1,195.0,39,106.0,70.0,0,0.0,26.97,0,...,1,0,8766,6438,6438,6438,8766,6438,8766,8766
1,6238,2,250.0,46,121.0,81.0,0,0.0,28.73,0,...,0,0,8766,8766,8766,8766,8766,8766,8766,8766
2,9428,1,245.0,48,127.5,80.0,1,20.0,25.34,0,...,0,0,8766,8766,8766,8766,8766,8766,8766,8766
3,10552,2,225.0,61,150.0,95.0,1,30.0,28.58,0,...,1,1,2956,2956,2956,2956,2089,2089,2956,0
4,11252,2,285.0,46,130.0,84.0,1,23.0,23.10,0,...,0,1,8766,8766,8766,8766,8766,8766,8766,4285
5,11263,2,228.0,43,180.0,110.0,0,0.0,30.30,0,...,1,1,8766,8766,5719,5719,8766,5719,8766,0
6,12629,2,205.0,63,138.0,71.0,0,0.0,33.11,0,...,0,1,373,8766,8766,373,8766,8766,8766,2212
7,12806,2,313.0,45,100.0,71.0,1,20.0,21.68,0,...,0,1,8766,8766,8766,8766,8766,8766,8766,8679
8,14367,1,260.0,52,141.5,89.0,0,0.0,26.36,0,...,0,1,8766,8766,8766,8766,8766,8766,8766,0
9,16365,1,225.0,43,162.0,107.0,1,30.0,23.61,0,...,0,1,8766,8766,8766,8766,8766,8766,8766,0
10,16799,2,254.0,50,133.0,76.0,0,0.0,22.91,0,...,0,0,8766,8766,8766,8766,8766,8766,8766,8766
11,19304,2,247.0,43,131.0,88.0,0,0.0,27.64,0,...,0,0,8766,8766,8766,8766,8766,8766,8766,8766
12,20375,1,294.0,46,142.0,94.0,1,15.0,26.31,0,...,0,1,8766,8766,8766,8766,8766,8766,8766,0
13,23727,2,332.0,41,124.0,88.0,0,0.0,31.31,0,...,0,1,5592,5592,5592,5592,5592,5592,5592,0
14,30928,2,221.0,38,140.0,90.0,1,20.0,21.35,0,...,0,1,146,146,146,146,146,146,146,0
15,33077,1,232.0,48,138.0,90.0,1,10.0,22.37,0,...,0,1,8766,8766,8766,8766,8766,8766,8766,0
16,33555,2,291.0,46,112.0,78.0,1,20.0,23.38,0,...,0,0,1442,1442,1442,1442,1442,1442,1442,1442
17,34689,2,195.0,38,122.0,84.5,1,5.0,23.24,0,...,0,1,8766,8766,8766,8766,8766,8766,8766,2157
18,36459,1,195.0,41,139.0,88.0,0,0.0,26.88,0,...,0,1,8766,8766,8766,8766,8766,8766,8766,1469
19,40435,2,190.0,42,108.0,70.5,1,30.0,21.59,0,...,0,1,8766,8766,8766,8766,8766,8766,8766,5933

In [3]:
df.columns

Index(['RANDID', 'SEX', 'TOTCHOL', 'AGE', 'SYSBP', 'DIABP', 'CURSMOKE',
       'CIGPDAY', 'BMI', 'DIABETES', 'BPMEDS', 'HEARTRTE', 'GLUCOSE',
       'PREVCHD', 'PREVAP', 'PREVMI', 'PREVSTRK', 'PREVHYP', 'TIME', 'PERIOD',
       'DEATH', 'ANGINA', 'HOSPMI', 'MI_FCHD', 'ANYCHD', 'STROKE', 'CVD',
       'HYPERTEN', 'TIMEAP', 'TIMEMI', 'TIMEMIFC', 'TIMECHD', 'TIMESTRK',
       'TIMECVD', 'TIMEDTH', 'TIMEHYP'],
      dtype='object')

In [4]:
death_df = df.set_index('RANDID')
#Remove columns not involved in analysis
death_df = death_df[['SEX', 'TOTCHOL', 'AGE', 'SYSBP', 'DIABP', 'CURSMOKE', 'CIGPDAY', 'BMI',
       'DIABETES', 'BPMEDS', 'HEARTRTE', 'GLUCOSE', 'PREVCHD', 'PREVAP',
       'PREVMI', 'PREVSTRK', 'PREVHYP', 'DEATH']]
death_df.head()

,SEX,TOTCHOL,AGE,SYSBP,DIABP,CURSMOKE,CIGPDAY,BMI,DIABETES,BPMEDS,HEARTRTE,GLUCOSE,PREVCHD,PREVAP,PREVMI,PREVSTRK,PREVHYP,DEATH
RANDID,,,,,,,,,,,,,,,,,,
2448,1,195.0,39,106.0,70.0,0,0.0,26.97,0,0.0,80.0,77.0,0,0,0,0,0,0
6238,2,250.0,46,121.0,81.0,0,0.0,28.73,0,0.0,95.0,76.0,0,0,0,0,0,0
9428,1,245.0,48,127.5,80.0,1,20.0,25.34,0,0.0,75.0,70.0,0,0,0,0,0,0
10552,2,225.0,61,150.0,95.0,1,30.0,28.58,0,0.0,65.0,103.0,0,0,0,0,1,1
11252,2,285.0,46,130.0,84.0,1,23.0,23.10,0,0.0,85.0,85.0,0,0,0,0,0,0

In [5]:
target = death_df["DEATH"]
target_names = ["negative", "positive"]

In [6]:
data = death_df.drop("DEATH",axis=1)
feature_names = data.columns
data.head()

,SEX,TOTCHOL,AGE,SYSBP,DIABP,CURSMOKE,CIGPDAY,BMI,DIABETES,BPMEDS,HEARTRTE,GLUCOSE,PREVCHD,PREVAP,PREVMI,PREVSTRK,PREVHYP
RANDID,,,,,,,,,,,,,,,,,
2448,1,195.0,39,106.0,70.0,0,0.0,26.97,0,0.0,80.0,77.0,0,0,0,0,0
6238,2,250.0,46,121.0,81.0,0,0.0,28.73,0,0.0,95.0,76.0,0,0,0,0,0
9428,1,245.0,48,127.5,80.0,1,20.0,25.34,0,0.0,75.0,70.0,0,0,0,0,0
10552,2,225.0,61,150.0,95.0,1,30.0,28.58,0,0.0,65.0,103.0,0,0,0,0,1
11252,2,285.0,46,130.0,84.0,1,23.0,23.10,0,0.0,85.0,85.0,0,0,0,0,0

In [7]:
# Split the data using train_test_split
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(data, target, random_state=49)

In [8]:
from sklearn.ensemble import RandomForestClassifier
# Create, fit, and score a Random Forest Classifier
rf = RandomForestClassifier(n_estimators=500, class_weight = "balanced")
rf = rf.fit(X_train, y_train)

print(f"Training Data Score: {rf.score(X_train, y_train)}")
print(f"Testing Data Score: {rf.score(X_test, y_test)}")

Training Data Score: 1.0
Testing Data Score: 0.7423625254582484

In [9]:
# calculate feature importance
importances = rf.feature_importances_
importances

array([0.02752745, 0.10676134, 0.21404607, 0.13041917, 0.09983832,
       0.01142171, 0.04481722, 0.11380539, 0.0094114 , 0.00478387,
       0.08309578, 0.1005185 , 0.0090567 , 0.00538249, 0.00293585,
       0.00240272, 0.03377603])

In [10]:
# sort the features by their importance
sorted(zip(rf.feature_importances_, feature_names), reverse=True)

[(0.2140460726938675, 'AGE'),
 (0.13041916682928242, 'SYSBP'),
 (0.1138053862246779, 'BMI'),
 (0.10676134118326136, 'TOTCHOL'),
 (0.10051850130676766, 'GLUCOSE'),
 (0.09983832206977207, 'DIABP'),
 (0.08309578184419698, 'HEARTRTE'),
 (0.04481721927919559, 'CIGPDAY'),
 (0.03377602799833821, 'PREVHYP'),
 (0.02752744528803359, 'SEX'),
 (0.011421705264192776, 'CURSMOKE'),
 (0.0094114030428642, 'DIABETES'),
 (0.009056700389393182, 'PREVCHD'),
 (0.005382488032360315, 'PREVAP'),
 (0.004783866236872683, 'BPMEDS'),
 (0.0029358501373054364, 'PREVMI'),
 (0.0024027221796181115, 'PREVSTRK')]

In [14]:
#Make predictions (0 = no event occurred, 1 = event occurred)
predictions = rf.predict(X_test)
death_predictions = pd.DataFrame({"Prediction": predictions, "Actual": y_test}).reset_index(drop=True)
death_predictions

     Prediction  Actual
0             0       0
1             0       1
2             0       0
3             0       0
4             0       0
..          ...     ...
977           0       1
978           1       1
979           0       0
980           0       1
981           0       0

[982 rows x 2 columns]

In [12]:
# Calculate classification report
from sklearn.metrics import classification_report
print(classification_report(y_test, predictions,
                            target_names=target_names))

              precision    recall  f1-score   support

    negative       0.75      0.90      0.82       630
    positive       0.72      0.45      0.56       352

    accuracy                           0.74       982
   macro avg       0.74      0.68      0.69       982
weighted avg       0.74      0.74      0.73       982

In [15]:
p0a0 = death_predictions.loc[(death_predictions['Prediction']==0) & (death_predictions['Actual']==0)]
p1a1 = death_predictions.loc[(death_predictions['Prediction']==1) & (death_predictions['Actual']==1)]
p0a1 = death_predictions.loc[(death_predictions['Prediction']==0) & (death_predictions['Actual']==1)]
p1a0 = death_predictions.loc[(death_predictions['Prediction']==1) & (death_predictions['Actual']==0)]

print(f"Event prediction and actual = 0:  {len(p0a0)}")
print(f"Event prediction and actual = 1:  {len(p1a1)}")
print(f"Event prediction = 0 and actual = 1:  {len(p0a1)}")
print(f"Event prediction = 1 and actual = 0:  {len(p1a0)}")

Event prediction and actual = 0:  569
Event prediction and actual = 1:  160
Event prediction = 0 and actual = 1:  192
Event prediction = 1 and actual = 0:  61

In [16]:
TP = len(p1a1)
TN = len(p0a0)
FP = len(p1a0)
FN = len(p0a1)

Accuracy = (TP + TN)/len(cvd_predictions)
Precision = TP/(TP + FP)
Recall = TP/(TP + FN)
F1 = 2*((Precision*Recall)/ (Precision+Recall))

print("Accuracy: %.3f" % Accuracy)
print("Precision: %.3f" % Precision)
print("Recall: %.3f" % Recall)
print("F1 Measure: %.3f" % F1)

Accuracy: 0.742
Precision: 0.724
Recall: 0.455
F1 Measure: 0.558

## Separate by gender

In [18]:
#filter df by gender (males = 1, females = 2)
male_death = death_df.loc[(death_df["SEX"] ==1)]
female_death = death_df.loc[(death_df["SEX"] ==2)]

In [19]:
male_death_df = male_death.drop('SEX', axis=1)
female_death_df = female_death.drop('SEX', axis=1)

In [20]:
male_target = male_death_df["DEATH"]
male_target_names = ["negative", "positive"]

female_target = female_death_df["DEATH"]
female_target_names = ["negative", "positive"]

In [22]:
male_data = male_death_df.drop("DEATH",axis=1)
male_feature_names = male_data.columns

female_data = female_death_df.drop("DEATH", axis=1)
female_feature_names = female_data.columns

In [23]:
# Split the data using train_test_split - males
from sklearn.model_selection import train_test_split

mX_train, mX_test, my_train, my_test = train_test_split(male_data, male_target, random_state=49)

In [24]:
# Create, fit, and score a Random Forest Classifier - males
mrf = RandomForestClassifier(n_estimators=500, class_weight = "balanced")
mrf = mrf.fit(mX_train, my_train)

print(f"Training Data Score (males): {mrf.score(mX_train, my_train)}")
print(f"Testing Data Score (males): {mrf.score(mX_test, my_test)}")

Training Data Score (males): 1.0
Testing Data Score (males): 0.7309417040358744

In [25]:
# sort the features by their importance
sorted(zip(mrf.feature_importances_, male_feature_names), reverse=True)

[(0.23445637031966915, 'AGE'),
 (0.13352485941205475, 'SYSBP'),
 (0.10913545130672588, 'TOTCHOL'),
 (0.10871914360109618, 'BMI'),
 (0.10316262045765295, 'GLUCOSE'),
 (0.09767648892858644, 'DIABP'),
 (0.08068406654939328, 'HEARTRTE'),
 (0.0532576756092951, 'CIGPDAY'),
 (0.02236813251171419, 'PREVHYP'),
 (0.019008286964617024, 'PREVCHD'),
 (0.011849537344895206, 'CURSMOKE'),
 (0.008708895870333862, 'PREVAP'),
 (0.007185092080661438, 'DIABETES'),
 (0.005862578010731587, 'PREVMI'),
 (0.0031431124187838865, 'BPMEDS'),
 (0.001257688613789117, 'PREVSTRK')]

In [28]:
#Make predictions (0 = no event occurred, 1 = event occurred)
m_predictions = mrf.predict(mX_test)
m_mi_fchd_predictions = pd.DataFrame({"Prediction": m_predictions, "Actual": my_test}).reset_index(drop=True)

mp0a0 = m_mi_fchd_predictions.loc[(m_mi_fchd_predictions['Prediction']==0) & (m_mi_fchd_predictions['Actual']==0)]
mp1a1 = m_mi_fchd_predictions.loc[(m_mi_fchd_predictions['Prediction']==1) & (m_mi_fchd_predictions['Actual']==1)]
mp0a1 = m_mi_fchd_predictions.loc[(m_mi_fchd_predictions['Prediction']==0) & (m_mi_fchd_predictions['Actual']==1)]
mp1a0 = m_mi_fchd_predictions.loc[(m_mi_fchd_predictions['Prediction']==1) & (m_mi_fchd_predictions['Actual']==0)]

print(f"Event prediction and actual = 0 (male):  {len(mp0a0)}")
print(f"Event prediction and actual = 1 (male):  {len(mp1a1)}")
print(f"Event prediction = 0 and actual = 1 (male):  {len(mp0a1)}")
print(f"Event prediction = 1 and actual = 0 (male):  {len(mp1a0)}")

Event prediction and actual = 0 (male):  212
Event prediction and actual = 1 (male):  114
Event prediction = 0 and actual = 1 (male):  71
Event prediction = 1 and actual = 0 (male):  49

In [29]:
# Calculate classification report
from sklearn.metrics import classification_report
print(classification_report(my_test, m_predictions,
                            target_names=male_target_names))

              precision    recall  f1-score   support

    negative       0.75      0.81      0.78       261
    positive       0.70      0.62      0.66       185

    accuracy                           0.73       446
   macro avg       0.72      0.71      0.72       446
weighted avg       0.73      0.73      0.73       446

In [30]:
# Split the data using train_test_split - females

fX_train, fX_test, fy_train, fy_test = train_test_split(female_data, female_target, random_state=49)

In [31]:
# Create, fit, and score a Random Forest Classifier - females
frf = RandomForestClassifier(n_estimators=500, class_weight = "balanced")
frf = frf.fit(fX_train, fy_train)

print(f"Training Data Score (females): {frf.score(fX_train, fy_train)}")
print(f"Testing Data Score (females): {frf.score(fX_test, fy_test)}")

Training Data Score (females): 1.0
Testing Data Score (females): 0.7486033519553073

In [32]:
# sort the features by their importance
sorted(zip(frf.feature_importances_, female_feature_names), reverse=True)

[(0.19567012456332963, 'AGE'),
 (0.15117309697711231, 'SYSBP'),
 (0.11573439040391022, 'BMI'),
 (0.11514224938095484, 'TOTCHOL'),
 (0.11178601980833879, 'DIABP'),
 (0.10108795014387358, 'GLUCOSE'),
 (0.08672397584737125, 'HEARTRTE'),
 (0.042522609669338636, 'CIGPDAY'),
 (0.040066686667735336, 'PREVHYP'),
 (0.012610329230691676, 'CURSMOKE'),
 (0.009445018721961839, 'DIABETES'),
 (0.007172328733684349, 'BPMEDS'),
 (0.0038996142024538033, 'PREVAP'),
 (0.003597053968901721, 'PREVCHD'),
 (0.0022729111950405417, 'PREVSTRK'),
 (0.0010956404853014242, 'PREVMI')]

In [33]:
#Make predictions (0 = no event occurred, 1 = event occurred)
f_predictions = frf.predict(fX_test)
f_mi_fchd_predictions = pd.DataFrame({"Prediction": f_predictions, "Actual": fy_test}).reset_index(drop=True)

fp0a0 = f_mi_fchd_predictions.loc[(f_mi_fchd_predictions['Prediction']==0) & (f_mi_fchd_predictions['Actual']==0)]
fp1a1 = f_mi_fchd_predictions.loc[(f_mi_fchd_predictions['Prediction']==1) & (f_mi_fchd_predictions['Actual']==1)]
fp0a1 = f_mi_fchd_predictions.loc[(f_mi_fchd_predictions['Prediction']==0) & (f_mi_fchd_predictions['Actual']==1)]
fp1a0 = f_mi_fchd_predictions.loc[(f_mi_fchd_predictions['Prediction']==1) & (f_mi_fchd_predictions['Actual']==0)]

print(f"Event prediction and actual = 0 (female):  {len(fp0a0)}")
print(f"Event prediction and actual = 1 (female):  {len(fp1a1)}")
print(f"Event prediction = 0 and actual = 1 (female):  {len(fp0a1)}")
print(f"Event prediction = 1 and actual = 0 (female):  {len(fp1a0)}")

Event prediction and actual = 0 (female):  354
Event prediction and actual = 1 (female):  48
Event prediction = 0 and actual = 1 (female):  102
Event prediction = 1 and actual = 0 (female):  33

In [34]:
# Calculate classification report
from sklearn.metrics import classification_report
print(classification_report(fy_test, f_predictions,
                            target_names=female_target_names))

              precision    recall  f1-score   support

    negative       0.78      0.91      0.84       387
    positive       0.59      0.32      0.42       150

    accuracy                           0.75       537
   macro avg       0.68      0.62      0.63       537
weighted avg       0.72      0.75      0.72       537