# hypertension - Random Forest

In [1]:
from sklearn import tree
import pandas as pd

In [2]:
#read in data set
df = pd.read_csv('../../Resources/HYP_final_data.csv')
df.head(20)

,RANDID,SEX,TOTCHOL,AGE,SYSBP,DIABP,CURSMOKE,CIGPDAY,BMI,DIABETES,...,PREVMI,PREVCHD,PREVAP,PREVSTRK,PREVHYP,TIME,PERIOD,DEATH,HYPERTEN,TIMEHYP
0,2448,1,195.0,39,106.0,70.0,0,0.0,26.97,0,...,0,0,0,0,0,0,1,0,0,8766
1,6238,2,250.0,46,121.0,81.0,0,0.0,28.73,0,...,0,0,0,0,0,0,1,0,0,8766
2,9428,1,245.0,48,127.5,80.0,1,20.0,25.34,0,...,0,0,0,0,0,0,1,0,0,8766
3,11252,2,285.0,46,130.0,84.0,1,23.0,23.10,0,...,0,0,0,0,0,0,1,0,1,4285
4,12629,2,205.0,63,138.0,71.0,0,0.0,33.11,0,...,0,0,0,0,0,0,1,0,1,2212
5,12806,2,313.0,45,100.0,71.0,1,20.0,21.68,0,...,0,0,0,0,0,0,1,0,1,8679
6,16799,2,254.0,50,133.0,76.0,0,0.0,22.91,0,...,0,0,0,0,0,0,1,0,0,8766
7,19304,2,247.0,43,131.0,88.0,0,0.0,27.64,0,...,0,0,0,0,0,0,1,0,0,8766
8,33555,2,291.0,46,112.0,78.0,1,20.0,23.38,0,...,0,0,0,0,0,0,1,1,0,1442
9,34689,2,195.0,38,122.0,84.5,1,5.0,23.24,0,...,0,0,0,0,0,0,1,0,1,2157
10,36459,1,195.0,41,139.0,88.0,0,0.0,26.88,0,...,0,0,0,0,0,0,1,0,1,1469
11,40435,2,190.0,42,108.0,70.5,1,30.0,21.59,0,...,0,0,0,0,0,0,1,0,1,5933
12,43770,2,234.0,52,148.0,78.0,0,0.0,34.17,0,...,0,0,0,0,0,0,1,1,1,723
13,45464,2,215.0,52,132.0,82.0,1,20.0,25.11,0,...,0,0,0,0,0,0,1,0,1,2177
14,54224,1,294.0,47,102.0,68.0,1,20.0,24.18,0,...,0,0,0,0,0,0,1,1,0,430
15,66472,2,247.0,60,130.0,88.0,0,0.0,30.36,0,...,0,0,0,0,0,0,1,1,1,1463
16,67905,1,295.0,36,102.0,68.0,1,35.0,28.15,0,...,0,0,0,0,0,0,1,0,1,2954
17,68194,1,226.0,43,115.0,85.5,1,43.0,27.57,0,...,0,0,0,0,0,0,1,0,1,6199
18,68397,1,227.0,40,125.0,90.0,0,0.0,23.62,0,...,1,1,1,0,0,0,1,0,1,785
19,70948,1,175.0,61,134.0,82.5,1,5.0,18.59,0,...,0,0,0,0,0,0,1,1,1,1451

In [3]:
df.columns

Index(['RANDID', 'SEX', 'TOTCHOL', 'AGE', 'SYSBP', 'DIABP', 'CURSMOKE',
       'CIGPDAY', 'BMI', 'DIABETES', 'BPMEDS', 'HEARTRTE', 'GLUCOSE', 'PREVMI',
       'PREVCHD', 'PREVAP', 'PREVSTRK', 'PREVHYP', 'TIME', 'PERIOD', 'DEATH',
       'HYPERTEN', 'TIMEHYP'],
      dtype='object')

In [6]:
HYP_df = df.set_index('RANDID')
#Remove columns not involved in analysis
#removed 'TIME', 'PERIOD', 'DEATH', 'TIMEHYP'

HYP_df = HYP_df[['SEX', 'TOTCHOL', 'AGE', 'SYSBP', 'DIABP', 'CURSMOKE', 'CIGPDAY', 'BMI',
       'DIABETES', 'BPMEDS', 'HEARTRTE', 'GLUCOSE', 'PREVMI', 'PREVCHD',
       'PREVAP', 'PREVSTRK', 'HYPERTEN']]
HYP_df.head()

,SEX,TOTCHOL,AGE,SYSBP,DIABP,CURSMOKE,CIGPDAY,BMI,DIABETES,BPMEDS,HEARTRTE,GLUCOSE,PREVMI,PREVCHD,PREVAP,PREVSTRK,HYPERTEN
RANDID,,,,,,,,,,,,,,,,,
2448,1,195.0,39,106.0,70.0,0,0.0,26.97,0,0.0,80.0,77.0,0,0,0,0,0
6238,2,250.0,46,121.0,81.0,0,0.0,28.73,0,0.0,95.0,76.0,0,0,0,0,0
9428,1,245.0,48,127.5,80.0,1,20.0,25.34,0,0.0,75.0,70.0,0,0,0,0,0
11252,2,285.0,46,130.0,84.0,1,23.0,23.10,0,0.0,85.0,85.0,0,0,0,0,1
12629,2,205.0,63,138.0,71.0,0,0.0,33.11,0,0.0,60.0,85.0,0,0,0,0,1

In [7]:
target = HYP_df["HYPERTEN"]
target_names = ["negative", "positive"]

In [8]:
data = HYP_df.drop("HYPERTEN",axis=1)
feature_names = data.columns
data.head()

,SEX,TOTCHOL,AGE,SYSBP,DIABP,CURSMOKE,CIGPDAY,BMI,DIABETES,BPMEDS,HEARTRTE,GLUCOSE,PREVMI,PREVCHD,PREVAP,PREVSTRK
RANDID,,,,,,,,,,,,,,,,
2448,1,195.0,39,106.0,70.0,0,0.0,26.97,0,0.0,80.0,77.0,0,0,0,0
6238,2,250.0,46,121.0,81.0,0,0.0,28.73,0,0.0,95.0,76.0,0,0,0,0
9428,1,245.0,48,127.5,80.0,1,20.0,25.34,0,0.0,75.0,70.0,0,0,0,0
11252,2,285.0,46,130.0,84.0,1,23.0,23.10,0,0.0,85.0,85.0,0,0,0,0
12629,2,205.0,63,138.0,71.0,0,0.0,33.11,0,0.0,60.0,85.0,0,0,0,0

In [9]:
# Split the data using train_test_split
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(data, target, random_state=49)

In [10]:
from sklearn.ensemble import RandomForestClassifier
# Create, fit, and score a Random Forest Classifier
rf = RandomForestClassifier(n_estimators=500, class_weight = "balanced")
rf = rf.fit(X_train, y_train)

print(f"Training Data Score: {rf.score(X_train, y_train)}")
print(f"Testing Data Score: {rf.score(X_test, y_test)}")

Training Data Score: 1.0
Testing Data Score: 0.7018072289156626

In [ ]:
# calculate feature importance
importances = rf.feature_importances_
importances

In [11]:
# sort the features by their importance
sorted(zip(rf.feature_importances_, feature_names), reverse=True)

[(0.19243380021113887, 'SYSBP'),
 (0.14307533697102873, 'DIABP'),
 (0.14120451140475032, 'BMI'),
 (0.12155472859755202, 'TOTCHOL'),
 (0.10722894615294883, 'GLUCOSE'),
 (0.10126787981270056, 'AGE'),
 (0.09856488604110537, 'HEARTRTE'),
 (0.05090347713281858, 'CIGPDAY'),
 (0.020638155051355894, 'SEX'),
 (0.011063351526259512, 'CURSMOKE'),
 (0.0035417307217933047, 'PREVCHD'),
 (0.0030181319738497706, 'PREVAP'),
 (0.0023039479015716565, 'DIABETES'),
 (0.0018757298899989513, 'PREVMI'),
 (0.001325386611127603, 'PREVSTRK'),
 (0.0, 'BPMEDS')]

In [12]:
#Make predictions (0 = no event occurred, 1 = event occurred)
predictions = rf.predict(X_test)
hyp_predictions = pd.DataFrame({"Prediction": predictions, "Actual": y_test}).reset_index(drop=True)
hyp_predictions

     Prediction  Actual
0             1       1
1             1       0
2             0       1
3             1       1
4             1       1
..          ...     ...
659           0       0
660           1       1
661           1       0
662           1       1
663           0       0

[664 rows x 2 columns]

In [13]:
# Calculate classification report
from sklearn.metrics import classification_report
print(classification_report(y_test, predictions,
                            target_names=target_names))

              precision    recall  f1-score   support

    negative       0.64      0.53      0.58       258
    positive       0.73      0.81      0.77       406

    accuracy                           0.70       664
   macro avg       0.69      0.67      0.67       664
weighted avg       0.70      0.70      0.70       664

In [14]:
p0a0 = hyp_predictions.loc[(hyp_predictions['Prediction']==0) & (hyp_predictions['Actual']==0)]
p1a1 = hyp_predictions.loc[(hyp_predictions['Prediction']==1) & (hyp_predictions['Actual']==1)]
p0a1 = hyp_predictions.loc[(hyp_predictions['Prediction']==0) & (hyp_predictions['Actual']==1)]
p1a0 = hyp_predictions.loc[(hyp_predictions['Prediction']==1) & (hyp_predictions['Actual']==0)]

In [15]:
print(f"Event prediction and actual = 0:  {len(p0a0)}")
print(f"Event prediction and actual = 1:  {len(p1a1)}")
print(f"Event prediction = 0 and actual = 1:  {len(p0a1)}")
print(f"Event prediction = 1 and actual = 0:  {len(p1a0)}")

Event prediction and actual = 0:  136
Event prediction and actual = 1:  330
Event prediction = 0 and actual = 1:  76
Event prediction = 1 and actual = 0:  122

In [ ]:
TP = len(p1a1)
TN = len(p0a0)
FP = len(p1a0)
FN = len(p0a1)

Accuracy = (TP + TN)/len(cvd_predictions)
Precision = TP/(TP + FP)
Recall = TP/(TP + FN)
F1 = 2*((Precision*Recall)/ (Precision+Recall))

print("Accuracy: %.3f" % Accuracy)
print("Precision: %.3f" % Precision)
print("Recall: %.3f" % Recall)
print("F1 Measure: %.3f" % F1)

## Separate by gender

In [ ]:
#filter df by gender (males = 1, females = 2)
male_mi_fchd = mi_fchd_df.loc[(mi_fchd_df["SEX"] ==1)]
female_mi_fchd = mi_fchd_df.loc[(mi_fchd_df["SEX"] ==2)]

In [ ]:
male_mi_fchd_df = male_mi_fchd.drop('SEX', axis=1)
female_mi_fchd_df = female_mi_fchd.drop('SEX', axis=1)

In [ ]:
female_mi_fchd_df

In [ ]:
male_target = male_mi_fchd_df["MI_FCHD"]
male_target_names = ["negative", "positive"]

female_target = female_mi_fchd_df["MI_FCHD"]
female_target_names = ["negative", "positive"]

In [ ]:
male_data = male_mi_fchd_df.drop("MI_FCHD",axis=1)
male_feature_names = male_data.columns

female_data = female_mi_fchd_df.drop("MI_FCHD", axis=1)
female_feature_names = female_data.columns

In [ ]:
# Split the data using train_test_split - males
from sklearn.model_selection import train_test_split

mX_train, mX_test, my_train, my_test = train_test_split(male_data, male_target, random_state=49)

In [ ]:
# Create, fit, and score a Random Forest Classifier - males
mrf = RandomForestClassifier(n_estimators=500, class_weight = "balanced")
mrf = mrf.fit(mX_train, my_train)

print(f"Training Data Score (males): {mrf.score(mX_train, my_train)}")
print(f"Testing Data Score (males): {mrf.score(mX_test, my_test)}")

In [ ]:
# sort the features by their importance
sorted(zip(mrf.feature_importances_, male_feature_names), reverse=True)

In [ ]:
# Calculate classification report
from sklearn.metrics import classification_report
print(classification_report(my_test, predictions,
                            target_names=target_names))

In [ ]:
#Make predictions (0 = no event occurred, 1 = event occurred)
m_predictions = mrf.predict(mX_test)
m_mi_fchd_predictions = pd.DataFrame({"Prediction": m_predictions, "Actual": my_test}).reset_index(drop=True)

mp0a0 = m_mi_fchd_predictions.loc[(m_mi_fchd_predictions['Prediction']==0) & (m_mi_fchd_predictions['Actual']==0)]
mp1a1 = m_mi_fchd_predictions.loc[(m_mi_fchd_predictions['Prediction']==1) & (m_mi_fchd_predictions['Actual']==1)]
mp0a1 = m_mi_fchd_predictions.loc[(m_mi_fchd_predictions['Prediction']==0) & (m_mi_fchd_predictions['Actual']==1)]
mp1a0 = m_mi_fchd_predictions.loc[(m_mi_fchd_predictions['Prediction']==1) & (m_mi_fchd_predictions['Actual']==0)]

print(f"Event prediction and actual = 0 (male):  {len(mp0a0)}")
print(f"Event prediction and actual = 1 (male):  {len(mp1a1)}")
print(f"Event prediction = 0 and actual = 1 (male):  {len(mp0a1)}")
print(f"Event prediction = 1 and actual = 0 (male):  {len(mp1a0)}")

In [ ]:
# Calculate classification report
from sklearn.metrics import classification_report
print(classification_report(my_test, m_predictions,
                            target_names=male_target_names))

In [ ]:
# Split the data using train_test_split - females

fX_train, fX_test, fy_train, fy_test = train_test_split(female_data, female_target, random_state=49)

In [ ]:
# Create, fit, and score a Random Forest Classifier - females
frf = RandomForestClassifier(n_estimators=500, class_weight = "balanced")
frf = frf.fit(fX_train, fy_train)

print(f"Training Data Score (females): {frf.score(fX_train, fy_train)}")
print(f"Testing Data Score (females): {frf.score(fX_test, fy_test)}")

In [ ]:
# sort the features by their importance
sorted(zip(frf.feature_importances_, female_feature_names), reverse=True)

In [ ]:
#Make predictions (0 = no event occurred, 1 = event occurred)
f_predictions = frf.predict(fX_test)
f_mi_fchd_predictions = pd.DataFrame({"Prediction": f_predictions, "Actual": fy_test}).reset_index(drop=True)

fp0a0 = f_mi_fchd_predictions.loc[(f_mi_fchd_predictions['Prediction']==0) & (f_mi_fchd_predictions['Actual']==0)]
fp1a1 = f_mi_fchd_predictions.loc[(f_mi_fchd_predictions['Prediction']==1) & (f_mi_fchd_predictions['Actual']==1)]
fp0a1 = f_mi_fchd_predictions.loc[(f_mi_fchd_predictions['Prediction']==0) & (f_mi_fchd_predictions['Actual']==1)]
fp1a0 = f_mi_fchd_predictions.loc[(f_mi_fchd_predictions['Prediction']==1) & (f_mi_fchd_predictions['Actual']==0)]

print(f"Event prediction and actual = 0 (female):  {len(fp0a0)}")
print(f"Event prediction and actual = 1 (female):  {len(fp1a1)}")
print(f"Event prediction = 0 and actual = 1 (female):  {len(fp0a1)}")
print(f"Event prediction = 1 and actual = 0 (female):  {len(fp1a0)}")

In [ ]:
# Calculate classification report
from sklearn.metrics import classification_report
print(classification_report(fy_test, f_predictions,
                            target_names=female_target_names))