# MI_FCHD - Random Forest

In [2]:
from sklearn import tree
import pandas as pd

In [3]:
#read in data set
df = pd.read_csv("Resources/MI_final_data.csv")
df.head(20)

,RANDID,SEX,TOTCHOL,AGE,SYSBP,DIABP,CURSMOKE,CIGPDAY,BMI,DIABETES,...,PREVMI,PREVSTRK,PREVHYP,TIME,PERIOD,DEATH,HOSPMI,MI_FCHD,TIMEMI,TIMEMIFC
0,2448,1,195.0,39,106.0,70.0,0,0.0,26.97,0,...,0,0,0,0,1,0,1,1,6438,6438
1,6238,2,250.0,46,121.0,81.0,0,0.0,28.73,0,...,0,0,0,0,1,0,0,0,8766,8766
2,9428,1,245.0,48,127.5,80.0,1,20.0,25.34,0,...,0,0,0,0,1,0,0,0,8766,8766
3,10552,2,225.0,61,150.0,95.0,1,30.0,28.58,0,...,0,0,1,0,1,1,0,0,2956,2956
4,11252,2,285.0,46,130.0,84.0,1,23.0,23.10,0,...,0,0,0,0,1,0,0,0,8766,8766
5,11263,2,228.0,43,180.0,110.0,0,0.0,30.30,0,...,0,0,1,0,1,0,0,1,8766,5719
6,12629,2,205.0,63,138.0,71.0,0,0.0,33.11,0,...,0,0,0,0,1,0,0,0,8766,8766
7,12806,2,313.0,45,100.0,71.0,1,20.0,21.68,0,...,0,0,0,0,1,0,0,0,8766,8766
8,14367,1,260.0,52,141.5,89.0,0,0.0,26.36,0,...,0,0,1,0,1,0,0,0,8766,8766
9,16365,1,225.0,43,162.0,107.0,1,30.0,23.61,0,...,0,0,1,0,1,0,0,0,8766,8766
10,16799,2,254.0,50,133.0,76.0,0,0.0,22.91,0,...,0,0,0,0,1,0,0,0,8766,8766
11,19304,2,247.0,43,131.0,88.0,0,0.0,27.64,0,...,0,0,0,0,1,0,0,0,8766,8766
12,20375,1,294.0,46,142.0,94.0,1,15.0,26.31,0,...,0,0,1,0,1,0,0,0,8766,8766
13,23727,2,332.0,41,124.0,88.0,0,0.0,31.31,0,...,0,0,1,0,1,1,0,0,5592,5592
14,30928,2,221.0,38,140.0,90.0,1,20.0,21.35,0,...,0,0,1,0,1,1,0,0,146,146
15,33077,1,232.0,48,138.0,90.0,1,10.0,22.37,0,...,0,0,1,0,1,0,0,0,8766,8766
16,33555,2,291.0,46,112.0,78.0,1,20.0,23.38,0,...,0,0,0,0,1,1,0,0,1442,1442
17,34689,2,195.0,38,122.0,84.5,1,5.0,23.24,0,...,0,0,0,0,1,0,0,0,8766,8766
18,36459,1,195.0,41,139.0,88.0,0,0.0,26.88,0,...,0,0,0,0,1,0,0,0,8766,8766
19,40435,2,190.0,42,108.0,70.5,1,30.0,21.59,0,...,0,0,0,0,1,0,0,0,8766,8766

In [4]:
df.columns

Index(['RANDID', 'SEX', 'TOTCHOL', 'AGE', 'SYSBP', 'DIABP', 'CURSMOKE',
       'CIGPDAY', 'BMI', 'DIABETES', 'BPMEDS', 'HEARTRTE', 'GLUCOSE',
       'PREVCHD', 'PREVAP', 'PREVMI', 'PREVSTRK', 'PREVHYP', 'TIME', 'PERIOD',
       'DEATH', 'HOSPMI', 'MI_FCHD', 'TIMEMI', 'TIMEMIFC'],
      dtype='object')

In [5]:
mi_fchd_df = df.set_index('RANDID')
#Remove columns not involved in analysis
mi_fchd_df = mi_fchd_df[['SEX', 'TOTCHOL', 'AGE', 'SYSBP', 'DIABP', 'CURSMOKE',
       'CIGPDAY', 'BMI', 'DIABETES', 'BPMEDS', 'HEARTRTE', 'GLUCOSE',
       'PREVCHD', 'PREVAP', 'PREVSTRK', 'PREVHYP', 'MI_FCHD']]
mi_fchd_df.head()

,SEX,TOTCHOL,AGE,SYSBP,DIABP,CURSMOKE,CIGPDAY,BMI,DIABETES,BPMEDS,HEARTRTE,GLUCOSE,PREVCHD,PREVAP,PREVSTRK,PREVHYP,MI_FCHD
RANDID,,,,,,,,,,,,,,,,,
2448,1,195.0,39,106.0,70.0,0,0.0,26.97,0,0.0,80.0,77.0,0,0,0,0,1
6238,2,250.0,46,121.0,81.0,0,0.0,28.73,0,0.0,95.0,76.0,0,0,0,0,0
9428,1,245.0,48,127.5,80.0,1,20.0,25.34,0,0.0,75.0,70.0,0,0,0,0,0
10552,2,225.0,61,150.0,95.0,1,30.0,28.58,0,0.0,65.0,103.0,0,0,0,1,0
11252,2,285.0,46,130.0,84.0,1,23.0,23.10,0,0.0,85.0,85.0,0,0,0,0,0

In [6]:
target = mi_fchd_df["MI_FCHD"]
target_names = ["negative", "positive"]

In [7]:
data = mi_fchd_df.drop("MI_FCHD",axis=1)
feature_names = data.columns
data.head()

,SEX,TOTCHOL,AGE,SYSBP,DIABP,CURSMOKE,CIGPDAY,BMI,DIABETES,BPMEDS,HEARTRTE,GLUCOSE,PREVCHD,PREVAP,PREVSTRK,PREVHYP
RANDID,,,,,,,,,,,,,,,,
2448,1,195.0,39,106.0,70.0,0,0.0,26.97,0,0.0,80.0,77.0,0,0,0,0
6238,2,250.0,46,121.0,81.0,0,0.0,28.73,0,0.0,95.0,76.0,0,0,0,0
9428,1,245.0,48,127.5,80.0,1,20.0,25.34,0,0.0,75.0,70.0,0,0,0,0
10552,2,225.0,61,150.0,95.0,1,30.0,28.58,0,0.0,65.0,103.0,0,0,0,1
11252,2,285.0,46,130.0,84.0,1,23.0,23.10,0,0.0,85.0,85.0,0,0,0,0

In [8]:
# Split the data using train_test_split
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(data, target, random_state=49)

In [9]:
from sklearn.ensemble import RandomForestClassifier
# Create, fit, and score a Random Forest Classifier
rf = RandomForestClassifier(n_estimators=500, class_weight = "balanced")
rf = rf.fit(X_train, y_train)

print(f"Training Data Score: {rf.score(X_train, y_train)}")
print(f"Testing Data Score: {rf.score(X_test, y_test)}")

Training Data Score: 1.0
Testing Data Score: 0.8471933471933472

In [10]:
# calculate feature importance
importances = rf.feature_importances_
importances

array([0.06626771, 0.14182157, 0.10114034, 0.13575066, 0.1113686 ,
       0.01162214, 0.05392304, 0.12706299, 0.0094351 , 0.00634802,
       0.09400906, 0.11161182, 0.00528069, 0.00443758, 0.00125606,
       0.01866463])

In [11]:
# sort the features by their importance
sorted(zip(rf.feature_importances_, feature_names), reverse=True)

[(0.14182156527024264, 'TOTCHOL'),
 (0.13575065737031938, 'SYSBP'),
 (0.1270629907407827, 'BMI'),
 (0.11161182342203115, 'GLUCOSE'),
 (0.11136859854177554, 'DIABP'),
 (0.10114033923760776, 'AGE'),
 (0.0940090569544612, 'HEARTRTE'),
 (0.06626771249188335, 'SEX'),
 (0.05392304439108814, 'CIGPDAY'),
 (0.018664633124067402, 'PREVHYP'),
 (0.01162213694568801, 'CURSMOKE'),
 (0.009435099620847216, 'DIABETES'),
 (0.006348019961938345, 'BPMEDS'),
 (0.005280690221527005, 'PREVCHD'),
 (0.004437575283799956, 'PREVAP'),
 (0.0012560564219402223, 'PREVSTRK')]

In [12]:
#Make predictions (0 = no event occurred, 1 = event occurred)
predictions = rf.predict(X_test)
cvd_predictions = pd.DataFrame({"Prediction": predictions, "Actual": y_test}).reset_index(drop=True)
cvd_predictions

     Prediction  Actual
0             0       0
1             0       0
2             0       1
3             0       0
4             0       0
..          ...     ...
957           0       0
958           0       0
959           0       0
960           0       1
961           0       0

[962 rows x 2 columns]

In [13]:
# Calculate classification report
from sklearn.metrics import classification_report
print(classification_report(y_test, predictions,
                            target_names=target_names))

              precision    recall  f1-score   support

    negative       0.85      1.00      0.92       815
    positive       0.50      0.01      0.01       147

    accuracy                           0.85       962
   macro avg       0.67      0.50      0.47       962
weighted avg       0.79      0.85      0.78       962

In [14]:
p0a0 = cvd_predictions.loc[(cvd_predictions['Prediction']==0) & (cvd_predictions['Actual']==0)]
p1a1 = cvd_predictions.loc[(cvd_predictions['Prediction']==1) & (cvd_predictions['Actual']==1)]
p0a1 = cvd_predictions.loc[(cvd_predictions['Prediction']==0) & (cvd_predictions['Actual']==1)]
p1a0 = cvd_predictions.loc[(cvd_predictions['Prediction']==1) & (cvd_predictions['Actual']==0)]

In [15]:
print(f"Event prediction and actual = 0:  {len(p0a0)}")
print(f"Event prediction and actual = 1:  {len(p1a1)}")
print(f"Event prediction = 0 and actual = 1:  {len(p0a1)}")
print(f"Event prediction = 1 and actual = 0:  {len(p1a0)}")

Event prediction and actual = 0:  814
Event prediction and actual = 1:  1
Event prediction = 0 and actual = 1:  146
Event prediction = 1 and actual = 0:  1

In [16]:
TP = len(p1a1)
TN = len(p0a0)
FP = len(p1a0)
FN = len(p0a1)

Accuracy = (TP + TN)/len(cvd_predictions)
Precision = TP/(TP + FP)
Recall = TP/(TP + FN)
F1 = 2*((Precision*Recall)/ (Precision+Recall))

print("Accuracy: %.3f" % Accuracy)
print("Precision: %.3f" % Precision)
print("Recall: %.3f" % Recall)
print("F1 Measure: %.3f" % F1)

Accuracy: 0.847
Precision: 0.500
Recall: 0.007
F1 Measure: 0.013

## Separate by gender

In [19]:
#filter df by gender (males = 1, females = 2)
male_mi_fchd = mi_fchd_df.loc[(mi_fchd_df["SEX"] ==1)]
female_mi_fchd = mi_fchd_df.loc[(mi_fchd_df["SEX"] ==2)]

In [20]:
male_mi_fchd_df = male_mi_fchd.drop('SEX', axis=1)
female_mi_fchd_df = female_mi_fchd.drop('SEX', axis=1)

In [36]:
female_mi_fchd_df

,TOTCHOL,AGE,SYSBP,DIABP,CURSMOKE,CIGPDAY,BMI,DIABETES,BPMEDS,HEARTRTE,GLUCOSE,PREVCHD,PREVAP,PREVSTRK,PREVHYP,MI_FCHD
RANDID,,,,,,,,,,,,,,,,
6238,250.0,46,121.0,81.0,0,0.0,28.73,0,0.0,95.0,76.0,0,0,0,0,0
10552,225.0,61,150.0,95.0,1,30.0,28.58,0,0.0,65.0,103.0,0,0,0,1,0
11252,285.0,46,130.0,84.0,1,23.0,23.10,0,0.0,85.0,85.0,0,0,0,0,0
11263,228.0,43,180.0,110.0,0,0.0,30.30,0,0.0,77.0,99.0,0,0,0,1,1
12629,205.0,63,138.0,71.0,0,0.0,33.11,0,0.0,60.0,85.0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9948301,266.0,63,167.0,94.0,0,0.0,25.23,0,0.0,95.0,94.0,0,0,0,1,0
9948320,265.0,52,137.5,84.5,0,0.0,26.91,0,0.0,72.0,86.0,0,0,0,0,0
9969773,260.0,50,190.0,130.0,0,0.0,43.67,1,0.0,85.0,260.0,0,0,0,1,1
9995546,269.0,52,133.5,83.0,0,0.0,21.47,0,0.0,80.0,107.0,0,0,0,0,1
9999312,196.0,39,133.0,86.0,1,30.0,20.91,0,0.0,85.0,80.0,0,0,0,0,0

In [22]:
male_target = male_mi_fchd_df["MI_FCHD"]
male_target_names = ["negative", "positive"]

female_target = female_mi_fchd_df["MI_FCHD"]
female_target_names = ["negative", "positive"]

In [23]:
male_data = male_mi_fchd_df.drop("MI_FCHD",axis=1)
male_feature_names = male_data.columns

female_data = female_mi_fchd_df.drop("MI_FCHD", axis=1)
female_feature_names = female_data.columns

In [24]:
# Split the data using train_test_split - males
from sklearn.model_selection import train_test_split

mX_train, mX_test, my_train, my_test = train_test_split(male_data, male_target, random_state=49)

In [25]:
# Create, fit, and score a Random Forest Classifier - males
mrf = RandomForestClassifier(n_estimators=500, class_weight = "balanced")
mrf = mrf.fit(mX_train, my_train)

print(f"Training Data Score (males): {mrf.score(mX_train, my_train)}")
print(f"Testing Data Score (males): {mrf.score(mX_test, my_test)}")

Training Data Score (males): 1.0
Testing Data Score (males): 0.7674418604651163

In [26]:
# sort the features by their importance
sorted(zip(mrf.feature_importances_, male_feature_names), reverse=True)

[(0.14444519698218572, 'TOTCHOL'),
 (0.14411509442858197, 'BMI'),
 (0.13959412393497506, 'SYSBP'),
 (0.12246229210457747, 'GLUCOSE'),
 (0.11939267277829313, 'DIABP'),
 (0.1122517000864525, 'AGE'),
 (0.10512975552878943, 'HEARTRTE'),
 (0.05775465222965014, 'CIGPDAY'),
 (0.016120085719872616, 'PREVHYP'),
 (0.013864365207892764, 'CURSMOKE'),
 (0.0064883860588677835, 'PREVCHD'),
 (0.006180379041484939, 'BPMEDS'),
 (0.005752815288170504, 'PREVAP'),
 (0.005131178188770074, 'DIABETES'),
 (0.0013173024214358689, 'PREVSTRK')]

In [ ]:
# Calculate classification report
from sklearn.metrics import classification_report
print(classification_report(my_test, predictions,
                            target_names=target_names))

In [28]:
#Make predictions (0 = no event occurred, 1 = event occurred)
m_predictions = mrf.predict(mX_test)
m_mi_fchd_predictions = pd.DataFrame({"Prediction": m_predictions, "Actual": my_test}).reset_index(drop=True)

mp0a0 = m_mi_fchd_predictions.loc[(m_mi_fchd_predictions['Prediction']==0) & (m_mi_fchd_predictions['Actual']==0)]
mp1a1 = m_mi_fchd_predictions.loc[(m_mi_fchd_predictions['Prediction']==1) & (m_mi_fchd_predictions['Actual']==1)]
mp0a1 = m_mi_fchd_predictions.loc[(m_mi_fchd_predictions['Prediction']==0) & (m_mi_fchd_predictions['Actual']==1)]
mp1a0 = m_mi_fchd_predictions.loc[(m_mi_fchd_predictions['Prediction']==1) & (m_mi_fchd_predictions['Actual']==0)]

print(f"Event prediction and actual = 0 (male):  {len(mp0a0)}")
print(f"Event prediction and actual = 1 (male):  {len(mp1a1)}")
print(f"Event prediction = 0 and actual = 1 (male):  {len(mp0a1)}")
print(f"Event prediction = 1 and actual = 0 (male):  {len(mp1a0)}")

Event prediction and actual = 0 (male):  327
Event prediction and actual = 1 (male):  3
Event prediction = 0 and actual = 1 (male):  97
Event prediction = 1 and actual = 0 (male):  3

In [34]:
# Calculate classification report
from sklearn.metrics import classification_report
print(classification_report(my_test, m_predictions,
                            target_names=male_target_names))

              precision    recall  f1-score   support

    negative       0.77      0.99      0.87       330
    positive       0.50      0.03      0.06       100

    accuracy                           0.77       430
   macro avg       0.64      0.51      0.46       430
weighted avg       0.71      0.77      0.68       430

In [30]:
# Split the data using train_test_split - females

fX_train, fX_test, fy_train, fy_test = train_test_split(female_data, female_target, random_state=49)

In [31]:
# Create, fit, and score a Random Forest Classifier - females
frf = RandomForestClassifier(n_estimators=500, class_weight = "balanced")
frf = frf.fit(fX_train, fy_train)

print(f"Training Data Score (females): {frf.score(fX_train, fy_train)}")
print(f"Testing Data Score (females): {frf.score(fX_test, fy_test)}")

Training Data Score (females): 1.0
Testing Data Score (females): 0.9043151969981238

In [32]:
# sort the features by their importance
sorted(zip(frf.feature_importances_, female_feature_names), reverse=True)

[(0.17543869258394568, 'TOTCHOL'),
 (0.14125510989003104, 'SYSBP'),
 (0.11647178196088341, 'DIABP'),
 (0.11270385998452136, 'AGE'),
 (0.1124838707583815, 'BMI'),
 (0.10878913173778372, 'GLUCOSE'),
 (0.0943711310686823, 'HEARTRTE'),
 (0.04815512748689885, 'PREVHYP'),
 (0.04577026889797974, 'CIGPDAY'),
 (0.015029980212036395, 'CURSMOKE'),
 (0.011972741372595182, 'BPMEDS'),
 (0.009414804082438034, 'DIABETES'),
 (0.0029389275620710733, 'PREVCHD'),
 (0.002917816212561697, 'PREVAP'),
 (0.0022867561891901154, 'PREVSTRK')]

In [33]:
#Make predictions (0 = no event occurred, 1 = event occurred)
f_predictions = frf.predict(fX_test)
f_mi_fchd_predictions = pd.DataFrame({"Prediction": f_predictions, "Actual": fy_test}).reset_index(drop=True)

fp0a0 = f_mi_fchd_predictions.loc[(f_mi_fchd_predictions['Prediction']==0) & (f_mi_fchd_predictions['Actual']==0)]
fp1a1 = f_mi_fchd_predictions.loc[(f_mi_fchd_predictions['Prediction']==1) & (f_mi_fchd_predictions['Actual']==1)]
fp0a1 = f_mi_fchd_predictions.loc[(f_mi_fchd_predictions['Prediction']==0) & (f_mi_fchd_predictions['Actual']==1)]
fp1a0 = f_mi_fchd_predictions.loc[(f_mi_fchd_predictions['Prediction']==1) & (f_mi_fchd_predictions['Actual']==0)]

print(f"Event prediction and actual = 0 (female):  {len(fp0a0)}")
print(f"Event prediction and actual = 1 (female):  {len(fp1a1)}")
print(f"Event prediction = 0 and actual = 1 (female):  {len(fp0a1)}")
print(f"Event prediction = 1 and actual = 0 (female):  {len(fp1a0)}")

Event prediction and actual = 0 (female):  482
Event prediction and actual = 1 (female):  0
Event prediction = 0 and actual = 1 (female):  51
Event prediction = 1 and actual = 0 (female):  0

In [35]:
# Calculate classification report
from sklearn.metrics import classification_report
print(classification_report(fy_test, f_predictions,
                            target_names=female_target_names))

              precision    recall  f1-score   support

    negative       0.90      1.00      0.95       482
    positive       0.00      0.00      0.00        51

    accuracy                           0.90       533
   macro avg       0.45      0.50      0.47       533
weighted avg       0.82      0.90      0.86       533

C:\Users\jtaum\Anaconda3\envs\PythonAdv\lib\site-packages\sklearn\metrics\_classification.py:1221: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))