# Myocardial Infarction - Random Forest

In [1]:
from sklearn import tree
import pandas as pd

In [2]:
#read in data set
df = pd.read_csv("../../Resources/MI_final_data.csv")
df.head(20)

,RANDID,SEX,TOTCHOL,AGE,SYSBP,DIABP,CURSMOKE,CIGPDAY,BMI,DIABETES,...,PREVMI,PREVSTRK,PREVHYP,TIME,PERIOD,DEATH,HOSPMI,MI_FCHD,TIMEMI,TIMEMIFC
0,2448,1,195.0,39,106.0,70.0,0,0.0,26.97,0,...,0,0,0,0,1,0,1,1,6438,6438
1,6238,2,250.0,46,121.0,81.0,0,0.0,28.73,0,...,0,0,0,0,1,0,0,0,8766,8766
2,9428,1,245.0,48,127.5,80.0,1,20.0,25.34,0,...,0,0,0,0,1,0,0,0,8766,8766
3,10552,2,225.0,61,150.0,95.0,1,30.0,28.58,0,...,0,0,1,0,1,1,0,0,2956,2956
4,11252,2,285.0,46,130.0,84.0,1,23.0,23.10,0,...,0,0,0,0,1,0,0,0,8766,8766
5,11263,2,228.0,43,180.0,110.0,0,0.0,30.30,0,...,0,0,1,0,1,0,0,1,8766,5719
6,12629,2,205.0,63,138.0,71.0,0,0.0,33.11,0,...,0,0,0,0,1,0,0,0,8766,8766
7,12806,2,313.0,45,100.0,71.0,1,20.0,21.68,0,...,0,0,0,0,1,0,0,0,8766,8766
8,14367,1,260.0,52,141.5,89.0,0,0.0,26.36,0,...,0,0,1,0,1,0,0,0,8766,8766
9,16365,1,225.0,43,162.0,107.0,1,30.0,23.61,0,...,0,0,1,0,1,0,0,0,8766,8766
10,16799,2,254.0,50,133.0,76.0,0,0.0,22.91,0,...,0,0,0,0,1,0,0,0,8766,8766
11,19304,2,247.0,43,131.0,88.0,0,0.0,27.64,0,...,0,0,0,0,1,0,0,0,8766,8766
12,20375,1,294.0,46,142.0,94.0,1,15.0,26.31,0,...,0,0,1,0,1,0,0,0,8766,8766
13,23727,2,332.0,41,124.0,88.0,0,0.0,31.31,0,...,0,0,1,0,1,1,0,0,5592,5592
14,30928,2,221.0,38,140.0,90.0,1,20.0,21.35,0,...,0,0,1,0,1,1,0,0,146,146
15,33077,1,232.0,48,138.0,90.0,1,10.0,22.37,0,...,0,0,1,0,1,0,0,0,8766,8766
16,33555,2,291.0,46,112.0,78.0,1,20.0,23.38,0,...,0,0,0,0,1,1,0,0,1442,1442
17,34689,2,195.0,38,122.0,84.5,1,5.0,23.24,0,...,0,0,0,0,1,0,0,0,8766,8766
18,36459,1,195.0,41,139.0,88.0,0,0.0,26.88,0,...,0,0,0,0,1,0,0,0,8766,8766
19,40435,2,190.0,42,108.0,70.5,1,30.0,21.59,0,...,0,0,0,0,1,0,0,0,8766,8766

In [3]:
MI_df = df.set_index('RANDID')
#Remove columns not involved in analysis
#removed 'Time', 'Period', 'Death', 'MI_FCHD', 'TIMEMI', 'TIMEMIFC'
MI_df = MI_df[['SEX', 'TOTCHOL', 'AGE', 'SYSBP', 'DIABP', 'CURSMOKE', 'CIGPDAY', 'BMI',
       'DIABETES', 'BPMEDS', 'HEARTRTE', 'GLUCOSE', 'PREVCHD', 'PREVAP',
       'PREVMI', 'PREVSTRK', 'PREVHYP', 'HOSPMI']]
MI_df.head()

,SEX,TOTCHOL,AGE,SYSBP,DIABP,CURSMOKE,CIGPDAY,BMI,DIABETES,BPMEDS,HEARTRTE,GLUCOSE,PREVCHD,PREVAP,PREVMI,PREVSTRK,PREVHYP,HOSPMI
RANDID,,,,,,,,,,,,,,,,,,
2448,1,195.0,39,106.0,70.0,0,0.0,26.97,0,0.0,80.0,77.0,0,0,0,0,0,1
6238,2,250.0,46,121.0,81.0,0,0.0,28.73,0,0.0,95.0,76.0,0,0,0,0,0,0
9428,1,245.0,48,127.5,80.0,1,20.0,25.34,0,0.0,75.0,70.0,0,0,0,0,0,0
10552,2,225.0,61,150.0,95.0,1,30.0,28.58,0,0.0,65.0,103.0,0,0,0,0,1,0
11252,2,285.0,46,130.0,84.0,1,23.0,23.10,0,0.0,85.0,85.0,0,0,0,0,0,0

In [4]:
target = MI_df["HOSPMI"]
target_names = ["No_MI", "MI"]

In [5]:
data = MI_df.drop("HOSPMI",axis=1)
feature_names = data.columns
data.head()

,SEX,TOTCHOL,AGE,SYSBP,DIABP,CURSMOKE,CIGPDAY,BMI,DIABETES,BPMEDS,HEARTRTE,GLUCOSE,PREVCHD,PREVAP,PREVMI,PREVSTRK,PREVHYP
RANDID,,,,,,,,,,,,,,,,,
2448,1,195.0,39,106.0,70.0,0,0.0,26.97,0,0.0,80.0,77.0,0,0,0,0,0
6238,2,250.0,46,121.0,81.0,0,0.0,28.73,0,0.0,95.0,76.0,0,0,0,0,0
9428,1,245.0,48,127.5,80.0,1,20.0,25.34,0,0.0,75.0,70.0,0,0,0,0,0
10552,2,225.0,61,150.0,95.0,1,30.0,28.58,0,0.0,65.0,103.0,0,0,0,0,1
11252,2,285.0,46,130.0,84.0,1,23.0,23.10,0,0.0,85.0,85.0,0,0,0,0,0

In [6]:
# Split the data using train_test_split
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(data, target, random_state=49)

In [7]:
# Create a Decision Tree Classifier
clf = tree.DecisionTreeClassifier()
clf = clf.fit(X_train, y_train)
clf.score(X_train, y_train)

1.0

In [8]:
# Fit the classifier to the data & print out the score of the model
print(f"Training Data Score: {clf.score(X_train, y_train)}")
print(f"Testing Data Score: {clf.score(X_test, y_test)}")

Training Data Score: 1.0
Testing Data Score: 0.8523908523908524

In [9]:
from sklearn.ensemble import RandomForestClassifier
# Create, fit, and score a Random Forest Classifier
rf = RandomForestClassifier(n_estimators=500, class_weight = "balanced")
rf = rf.fit(X_train, y_train)

print(f"Training Data Score: {rf.score(X_train, y_train)}")
print(f"Testing Data Score: {rf.score(X_test, y_test)}")

Training Data Score: 1.0
Testing Data Score: 0.9137214137214137

In [10]:
# calculate feature importance
importances = rf.feature_importances_
importances

array([0.07554724, 0.14116398, 0.09815622, 0.11924843, 0.10968959,
       0.01389779, 0.06447052, 0.12860629, 0.00795075, 0.00551376,
       0.09834427, 0.11038541, 0.00406131, 0.00361172, 0.        ,
       0.00136168, 0.01799103])

In [11]:
# sort the features by their importance
sorted(zip(rf.feature_importances_, feature_names), reverse=True)

[(0.14116398387587145, 'TOTCHOL'),
 (0.12860629145938182, 'BMI'),
 (0.11924842847643732, 'SYSBP'),
 (0.11038540907231156, 'GLUCOSE'),
 (0.10968958985277467, 'DIABP'),
 (0.09834426831877349, 'HEARTRTE'),
 (0.09815622378620087, 'AGE'),
 (0.07554724367468688, 'SEX'),
 (0.06447052442405235, 'CIGPDAY'),
 (0.01799103291633673, 'PREVHYP'),
 (0.013897786529947482, 'CURSMOKE'),
 (0.007950752862776137, 'DIABETES'),
 (0.005513757085780291, 'BPMEDS'),
 (0.00406130968982082, 'PREVCHD'),
 (0.0036117205006880528, 'PREVAP'),
 (0.0013616774741600681, 'PREVSTRK'),
 (0.0, 'PREVMI')]

In [12]:
#Make predictions (0 = no event occurred, 1 = event occurred)
predictions = rf.predict(X_test)
MI_predictions = pd.DataFrame({"Prediction": predictions, "Actual": y_test}).reset_index(drop=True)
MI_predictions

     Prediction  Actual
0             0       0
1             0       0
2             0       1
3             0       0
4             0       0
..          ...     ...
957           0       0
958           0       0
959           0       0
960           0       1
961           0       0

[962 rows x 2 columns]

In [13]:
no_event = MI_predictions.loc[(MI_predictions['Prediction']==0) & (MI_predictions['Actual']==0)]
event = MI_predictions.loc[(MI_predictions['Prediction']==1) & (MI_predictions['Actual']==1)]
p0a1 = MI_predictions.loc[(MI_predictions['Prediction']==0) & (MI_predictions['Actual']==1)]
p1a0 = MI_predictions.loc[(MI_predictions['Prediction']==1) & (MI_predictions['Actual']==0)]

In [14]:
print(f"Event prediction and actual = 0:  {len(no_event)}")
print(f"Event prediction and actual = 1:  {len(event)}")
print(f"Event prediction = 0 and actual = 1:  {len(p0a1)}")
print(f"Event prediction = 1 and actual = 0:  {len(p1a0)}")

Event prediction and actual = 0:  879
Event prediction and actual = 1:  0
Event prediction = 0 and actual = 1:  83
Event prediction = 1 and actual = 0:  0

In [16]:
# Calculate classification report
from sklearn.metrics import classification_report
print(classification_report(y_test, predictions,
                            target_names=target_names))

              precision    recall  f1-score   support

       No_MI       0.91      1.00      0.95       879
          MI       0.00      0.00      0.00        83

    accuracy                           0.91       962
   macro avg       0.46      0.50      0.48       962
weighted avg       0.83      0.91      0.87       962

C:\Users\jtaum\Anaconda3\envs\PythonAdv\lib\site-packages\sklearn\metrics\_classification.py:1221: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))