# stroke - Random Forest

In [1]:
from sklearn import tree
import pandas as pd

In [2]:
#read in data set
df = pd.read_csv('../../Resources/STROKE_final_data.csv')
df.head()

,RANDID,SEX,TOTCHOL,AGE,SYSBP,DIABP,CURSMOKE,CIGPDAY,BMI,DIABETES,...,GLUCOSE,PREVCHD,PREVAP,PREVMI,PREVSTRK,PREVHYP,TIME,PERIOD,DEATH,STROKE
0,2448,1,195.0,39,106.0,70.0,0,0.0,26.97,0,...,77.0,0,0,0,0,0,0,1,0,0
1,6238,2,250.0,46,121.0,81.0,0,0.0,28.73,0,...,76.0,0,0,0,0,0,0,1,0,0
2,9428,1,245.0,48,127.5,80.0,1,20.0,25.34,0,...,70.0,0,0,0,0,0,0,1,0,0
3,10552,2,225.0,61,150.0,95.0,1,30.0,28.58,0,...,103.0,0,0,0,0,1,0,1,1,1
4,11252,2,285.0,46,130.0,84.0,1,23.0,23.10,0,...,85.0,0,0,0,0,0,0,1,0,0

In [3]:
df.columns

Index(['RANDID', 'SEX', 'TOTCHOL', 'AGE', 'SYSBP', 'DIABP', 'CURSMOKE',
       'CIGPDAY', 'BMI', 'DIABETES', 'BPMEDS', 'HEARTRTE', 'GLUCOSE',
       'PREVCHD', 'PREVAP', 'PREVMI', 'PREVSTRK', 'PREVHYP', 'TIME', 'PERIOD',
       'DEATH', 'STROKE'],
      dtype='object')

In [4]:
stroke_df = df.set_index('RANDID')
#Remove columns not involved in analysis
#removed 'TIME', 'PERIOD', 'DEATH', 'TIMEHYP'

stroke_df = stroke_df[['SEX', 'TOTCHOL', 'AGE', 'SYSBP', 'DIABP', 'CURSMOKE', 'CIGPDAY', 'BMI',
       'DIABETES', 'BPMEDS', 'HEARTRTE', 'GLUCOSE', 'PREVCHD', 'PREVAP',
       'PREVMI', 'PREVHYP', 'STROKE']]
stroke_df.head()

,SEX,TOTCHOL,AGE,SYSBP,DIABP,CURSMOKE,CIGPDAY,BMI,DIABETES,BPMEDS,HEARTRTE,GLUCOSE,PREVCHD,PREVAP,PREVMI,PREVHYP,STROKE
RANDID,,,,,,,,,,,,,,,,,
2448,1,195.0,39,106.0,70.0,0,0.0,26.97,0,0.0,80.0,77.0,0,0,0,0,0
6238,2,250.0,46,121.0,81.0,0,0.0,28.73,0,0.0,95.0,76.0,0,0,0,0,0
9428,1,245.0,48,127.5,80.0,1,20.0,25.34,0,0.0,75.0,70.0,0,0,0,0,0
10552,2,225.0,61,150.0,95.0,1,30.0,28.58,0,0.0,65.0,103.0,0,0,0,1,1
11252,2,285.0,46,130.0,84.0,1,23.0,23.10,0,0.0,85.0,85.0,0,0,0,0,0

In [5]:
target = stroke_df["STROKE"]
target_names = ["negative", "positive"]

In [6]:
data = stroke_df.drop("STROKE",axis=1)
feature_names = data.columns
data.head()

,SEX,TOTCHOL,AGE,SYSBP,DIABP,CURSMOKE,CIGPDAY,BMI,DIABETES,BPMEDS,HEARTRTE,GLUCOSE,PREVCHD,PREVAP,PREVMI,PREVHYP
RANDID,,,,,,,,,,,,,,,,
2448,1,195.0,39,106.0,70.0,0,0.0,26.97,0,0.0,80.0,77.0,0,0,0,0
6238,2,250.0,46,121.0,81.0,0,0.0,28.73,0,0.0,95.0,76.0,0,0,0,0
9428,1,245.0,48,127.5,80.0,1,20.0,25.34,0,0.0,75.0,70.0,0,0,0,0
10552,2,225.0,61,150.0,95.0,1,30.0,28.58,0,0.0,65.0,103.0,0,0,0,1
11252,2,285.0,46,130.0,84.0,1,23.0,23.10,0,0.0,85.0,85.0,0,0,0,0

In [7]:
# Split the data using train_test_split
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(data, target, random_state=49)

In [8]:
from sklearn.ensemble import RandomForestClassifier
# Create, fit, and score a Random Forest Classifier
rf = RandomForestClassifier(n_estimators=500, class_weight = "balanced")
rf = rf.fit(X_train, y_train)

print(f"Training Data Score: {rf.score(X_train, y_train)}")
print(f"Testing Data Score: {rf.score(X_test, y_test)}")

Training Data Score: 1.0
Testing Data Score: 0.9057377049180327

In [ ]:
# calculate feature importance
importances = rf.feature_importances_
importances

In [9]:
# sort the features by their importance
sorted(zip(rf.feature_importances_, feature_names), reverse=True)

[(0.16497785658987005, 'AGE'),
 (0.1336477531023841, 'SYSBP'),
 (0.12463772885300448, 'BMI'),
 (0.11449432667524326, 'DIABP'),
 (0.11071881927327555, 'TOTCHOL'),
 (0.10545432669880271, 'GLUCOSE'),
 (0.09684373984099397, 'HEARTRTE'),
 (0.05004085518491279, 'CIGPDAY'),
 (0.03358591511195039, 'PREVHYP'),
 (0.0177251654068683, 'SEX'),
 (0.013078050187166854, 'CURSMOKE'),
 (0.009647919099645588, 'DIABETES'),
 (0.007417111755926564, 'BPMEDS'),
 (0.006855862331030902, 'PREVCHD'),
 (0.005927744783115408, 'PREVAP'),
 (0.004946825105809292, 'PREVMI')]

In [10]:
#Make predictions (0 = no event occurred, 1 = event occurred)
predictions = rf.predict(X_test)
stroke_predictions = pd.DataFrame({"Prediction": predictions, "Actual": y_test}).reset_index(drop=True)
stroke_predictions

     Prediction  Actual
0             0       0
1             0       1
2             0       0
3             0       0
4             0       0
..          ...     ...
971           0       0
972           0       0
973           0       0
974           0       0
975           0       1

[976 rows x 2 columns]

In [11]:
# Calculate classification report
from sklearn.metrics import classification_report
print(classification_report(y_test, predictions,
                            target_names=target_names))

              precision    recall  f1-score   support

    negative       0.91      1.00      0.95       884
    positive       0.00      0.00      0.00        92

    accuracy                           0.91       976
   macro avg       0.45      0.50      0.48       976
weighted avg       0.82      0.91      0.86       976

C:\Users\jtaum\Anaconda3\envs\PythonAdv\lib\site-packages\sklearn\metrics\_classification.py:1221: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

In [12]:
p0a0 = stroke_predictions.loc[(stroke_predictions['Prediction']==0) & (stroke_predictions['Actual']==0)]
p1a1 = stroke_predictions.loc[(stroke_predictions['Prediction']==1) & (stroke_predictions['Actual']==1)]
p0a1 = stroke_predictions.loc[(stroke_predictions['Prediction']==0) & (stroke_predictions['Actual']==1)]
p1a0 = stroke_predictions.loc[(stroke_predictions['Prediction']==1) & (stroke_predictions['Actual']==0)]

print(f"Event prediction = 0 and actual = 0:  {len(p0a0)}")
print(f"Event prediction = 1 and actual = 1:  {len(p1a1)}")
print(f"Event prediction = 0 and actual = 1:  {len(p0a1)}")
print(f"Event prediction = 1 and actual = 0:  {len(p1a0)}")

Event prediction = 0 and actual = 0:  884
Event prediction = 1 and actual = 1:  0
Event prediction = 0 and actual = 1:  92
Event prediction = 1 and actual = 0:  0