In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('../Resources/HYP_final_data.csv')
df.head()

,RANDID,SEX,TOTCHOL,AGE,SYSBP,DIABP,CURSMOKE,CIGPDAY,BMI,DIABETES,...,GLUCOSE,PREVCHD,PREVAP,PREVSTRK,PREVHYP,TIME,PERIOD,DEATH,HYPERTEN,TIMEHYP
0,2448,1,195.0,39,106.0,70.0,0,0.0,26.97,0,...,77.0,0,0,0,0,0,1,0,0,8766
1,6238,2,250.0,46,121.0,81.0,0,0.0,28.73,0,...,76.0,0,0,0,0,0,1,0,0,8766
2,9428,1,245.0,48,127.5,80.0,1,20.0,25.34,0,...,70.0,0,0,0,0,0,1,0,0,8766
3,11252,2,285.0,46,130.0,84.0,1,23.0,23.10,0,...,85.0,0,0,0,0,0,1,0,1,4285
4,12629,2,205.0,63,138.0,71.0,0,0.0,33.11,0,...,85.0,0,0,0,0,0,1,0,1,2212

In [3]:
HYP_df = df.set_index('RANDID')
HYP_df.head()

,SEX,TOTCHOL,AGE,SYSBP,DIABP,CURSMOKE,CIGPDAY,BMI,DIABETES,BPMEDS,...,GLUCOSE,PREVCHD,PREVAP,PREVSTRK,PREVHYP,TIME,PERIOD,DEATH,HYPERTEN,TIMEHYP
RANDID,,,,,,,,,,,,,,,,,,,,,
2448,1,195.0,39,106.0,70.0,0,0.0,26.97,0,0.0,...,77.0,0,0,0,0,0,1,0,0,8766
6238,2,250.0,46,121.0,81.0,0,0.0,28.73,0,0.0,...,76.0,0,0,0,0,0,1,0,0,8766
9428,1,245.0,48,127.5,80.0,1,20.0,25.34,0,0.0,...,70.0,0,0,0,0,0,1,0,0,8766
11252,2,285.0,46,130.0,84.0,1,23.0,23.10,0,0.0,...,85.0,0,0,0,0,0,1,0,1,4285
12629,2,205.0,63,138.0,71.0,0,0.0,33.11,0,0.0,...,85.0,0,0,0,0,0,1,0,1,2212

In [5]:
#Number of events for Hypertension calls and number of non-events
HYP_count = HYP_df.loc[(HYP_df['HYPERTEN']==1)]
no_event_count = HYP_df.loc[(HYP_df['HYPERTEN']==0)]

print(f'Subjects afflcited with HYP: {len(HYP_count)}')
print(f'Subjects with no HYP events: {len(no_event_count)}')

Subjects afflcited with HYP: 1608
Subjects with no HYP events: 1046

In [6]:
HYP_df.columns

Index(['SEX', 'TOTCHOL', 'AGE', 'SYSBP', 'DIABP', 'CURSMOKE', 'CIGPDAY', 'BMI',
       'DIABETES', 'BPMEDS', 'HEARTRTE', 'GLUCOSE', 'PREVCHD', 'PREVAP',
       'PREVSTRK', 'PREVHYP', 'TIME', 'PERIOD', 'DEATH', 'HYPERTEN',
       'TIMEHYP'],
      dtype='object')

In [8]:
HYP_reg_df = HYP_df[['SEX', 'TOTCHOL', 'AGE', 'SYSBP', 'DIABP', 'CURSMOKE', 'CIGPDAY', 'BMI',
                    'DIABETES', 'BPMEDS', 'HEARTRTE', 'GLUCOSE', 'PREVCHD', 'PREVAP', 
                    'PREVMI', 'PREVSTRK', 'PREVHYP', 'HYPERTEN']]
HYP_reg_df.head()

KeyError: "['PREVMI'] not in index"